import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { CreateLinkRequest, LinkMutationResponse, ProjectLinkDto, ProjectTaskDto } from "../../contracts/projects";
import { recalculateFinishStartDependencies, recalculateHierarchy, scheduleLeaf, SchedulingError } from "../../domain/scheduling";
import { projectCalendarDto, resolveProjectWorkingCalendar } from "../calendars/calendar-resolution-core";
import { EditSessionRepository, ProjectRepository } from "../repositories/project-repository-core";
import { ScheduleRepository, type LinkRecord, type TaskRecord } from "../repositories/schedule-repository-core";
import { ResourceCatalogRepository } from "../repositories/resource-catalog-repository-core";
import { EditSessionInvalidError, PersistedScheduleInvalidError, RevisionMismatchError, type AuthorizedEditSession } from "./project-service-core";

export class LinkNotFoundError extends Error {}
export class LinkConflictError extends Error { constructor(readonly code:string){super(code);} }

function taskDtos(tasks:readonly TaskRecord[]):ProjectTaskDto[]{const ext=new Map(tasks.map(t=>[t.id,t.externalId]));return tasks.map(t=>({taskId:t.publicId,externalId:t.externalId,name:t.name,description:t.description,url:t.url,type:t.type,scheduleMode:t.scheduleMode,requestedStart:t.requestedStart,start:t.startDate,end:t.endDate,duration:t.duration,progress:t.progress,parentExternalId:t.parentId===null?null:ext.get(t.parentId)??null,siblingOrder:t.sortOrder}));}
function linkDtos(links:readonly LinkRecord[],tasks:readonly TaskRecord[]):ProjectLinkDto[]{const ext=new Map(tasks.map(t=>[t.id,t.externalId]));return links.map(l=>({id:l.publicId,predecessorExternalId:ext.get(l.predecessorTaskId)!,successorExternalId:ext.get(l.successorTaskId)!,type:"FS",lag:0}));}

export class LinkService{
 private projects:ProjectRepository; private sessions:EditSessionRepository; private schedules:ScheduleRepository; private resources:ResourceCatalogRepository;
 constructor(private database:Database.Database,private clock=()=>new Date()){this.projects=new ProjectRepository(database);this.sessions=new EditSessionRepository(database);this.schedules=new ScheduleRepository(database);this.resources=new ResourceCatalogRepository(database);}
 private requireProject(a:AuthorizedEditSession,now:Date){const s=this.sessions.findById(a.sessionId),p=this.projects.findCredentialById(a.projectId);if(!s||!p||s.revokedAt!==null||!s.tokenHash.equals(a.tokenHash)||s.projectId!==p.id||s.authVersion!==p.authVersion||p.publicId!==a.projectPublicId||p.authVersion!==a.projectAuthVersion||Date.parse(s.expiresAt)<=now.getTime())throw new EditSessionInvalidError();return p;}
 private recalc(projectId:number,now:string){const cal=resolveProjectWorkingCalendar(this.database,projectId),records=this.schedules.listTasks(projectId);const base=records.map(t=>{if(t.type==="summary")return t;if(t.requestedStart===null)throw new PersistedScheduleInvalidError();const s=scheduleLeaf({type:t.type,requestedStart:t.requestedStart,duration:t.duration,scheduleMode:t.scheduleMode},cal);return{...t,startDate:s.start,endDate:s.end};});let dep;try{dep=recalculateFinishStartDependencies(taskDtos(base),linkDtos(this.schedules.listLinks(projectId),base),cal);}catch(e){if(e instanceof SchedulingError)throw e;throw new PersistedScheduleInvalidError();}if(dep.manualConflicts.length)throw new LinkConflictError("MANUAL_DEPENDENCY_CONFLICT");const changed=new Set<string>(),byId=new Map(records.map(t=>[t.publicId,t]));for(const t of dep.tasks){if(t.type==="summary")continue;const cur=byId.get(t.taskId);if(!cur)throw new PersistedScheduleInvalidError();if(cur.startDate===t.start&&cur.endDate===t.end)continue;const assignments=this.resources.listAssignments(projectId).filter(a=>a.taskPublicId===cur.publicId&&a.kind==="resource");if(assignments.some(a=>(a.assignmentStart!==null&&(a.assignmentStart<t.start||a.assignmentStart>t.end))||(a.assignmentEnd!==null&&(a.assignmentEnd<t.start||a.assignmentEnd>t.end))))throw new LinkConflictError("RESOURCE_ASSIGNMENT_SCHEDULE_CONFLICT");if(!this.schedules.updateTask(projectId,t.taskId,{name:cur.name,type:cur.type,scheduleMode:cur.scheduleMode,requestedStart:cur.requestedStart,startDate:t.start,endDate:t.end,duration:cur.duration,progress:cur.progress,updatedAt:now}))throw new PersistedScheduleInvalidError();changed.add(cur.externalId);}const refreshed=this.schedules.listTasks(projectId),derived=recalculateHierarchy(taskDtos(refreshed),cal),rb=new Map(refreshed.map(t=>[t.publicId,t]));for(const t of derived){if(t.type!=="summary")continue;const cur=rb.get(t.taskId);if(!cur)throw new PersistedScheduleInvalidError();if(cur.startDate===t.start&&cur.endDate===t.end&&cur.duration===t.duration&&cur.progress===t.progress)continue;if(!this.schedules.updateSummarySchedule(projectId,t.taskId,{startDate:t.start,endDate:t.end,duration:t.duration,progress:t.progress,updatedAt:now}))throw new PersistedScheduleInvalidError();changed.add(cur.externalId);}return[...changed];}
 private response(projectId:number,changedTaskExternalIds:string[],deletedLinkIds:string[],kind:"linkCreate"|"linkDelete"):LinkMutationResponse{const p=this.projects.findById(projectId);if(!p)throw new PersistedScheduleInvalidError();const tasks=this.schedules.listTasks(projectId);return{data:{project:{publicId:p.publicId,name:p.name,description:p.description,status:p.status,revision:p.revision,calendar:projectCalendarDto(this.database,projectId)},tasks:taskDtos(tasks),links:linkDtos(this.schedules.listLinks(projectId),tasks),warnings:[],operation:{kind,changedTaskExternalIds,deletedLinkIds}}};}
 create(a:AuthorizedEditSession,rev:number,input:CreateLinkRequest){return this.database.transaction(()=>{const d=this.clock(),now=d.toISOString(),p=this.requireProject(a,d);if(p.revision!==rev)throw new RevisionMismatchError();const pre=this.schedules.findTaskByExternalId(p.id,input.predecessorExternalId),suc=this.schedules.findTaskByExternalId(p.id,input.successorExternalId);if(!pre||!suc)throw new LinkConflictError("MISSING_DEPENDENCY");if(pre.id===suc.id)throw new LinkConflictError("SELF_DEPENDENCY");if(pre.type==="summary"||suc.type==="summary")throw new LinkConflictError("SUMMARY_DEPENDENCY_ENDPOINT");if(this.schedules.listLinks(p.id).some(l=>l.predecessorTaskId===pre.id&&l.successorTaskId===suc.id))throw new LinkConflictError("DUPLICATE_DEPENDENCY");this.schedules.insertLink({publicId:randomUUID(),projectId:p.id,predecessorTaskId:pre.id,successorTaskId:suc.id,type:"FS",lag:0,createdAt:now,updatedAt:now});const changed=this.recalc(p.id,now);if(!this.projects.advanceRevision(p.id,rev,now))throw new RevisionMismatchError();return this.response(p.id,changed,[],"linkCreate");}).immediate();}
 delete(a:AuthorizedEditSession,rev:number,id:string){return this.database.transaction(()=>{const d=this.clock(),now=d.toISOString(),p=this.requireProject(a,d);if(p.revision!==rev)throw new RevisionMismatchError();if(!this.schedules.findLinkByPublicId(p.id,id)||!this.schedules.deleteLink(p.id,id))throw new LinkNotFoundError();const changed=this.recalc(p.id,now);if(!this.projects.advanceRevision(p.id,rev,now))throw new RevisionMismatchError();return this.response(p.id,changed,[id],"linkDelete");}).immediate();}
}
