import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { CopyProjectRequest,CopyProjectResponse,ProjectTaskDto } from "../../contracts/projects";
import { createWorkingCalendar,recalculateHierarchy } from "../../domain/scheduling";
import { EditSessionRepository,ProjectRepository } from "../repositories/project-repository-core";
import { ScheduleRepository,type TaskRecord } from "../repositories/schedule-repository-core";
import { hashEditPassword,type PasswordHashRecord } from "../security/password-core";
import { createSessionToken,sessionExpiry,type NewSessionToken } from "../security/session-core";
import { isCanonicalUuidV4 } from "./project-contract";
import { EditSessionInvalidError,PersistedScheduleInvalidError,RevisionMismatchError,recalculatePersistedHierarchy,type AuthorizedEditSession } from "./project-service-core";
const ID_ATTEMPTS=3,MAX_PROJECT_TASKS=5000;
export interface ProjectCopyServiceOptions{clock?:()=>Date;generatePublicId?:()=>string;generateTaskPublicId?:()=>string;generateLinkPublicId?:()=>string;hashPassword?:(password:string)=>Promise<PasswordHashRecord>;generateSessionToken?:()=>NewSessionToken}
export interface CopiedProject{response:CopyProjectResponse;rawSessionToken:string}
function dtoTasks(tasks:readonly TaskRecord[]):ProjectTaskDto[]{const externalById=new Map(tasks.map(t=>[t.id,t.externalId]));return tasks.map(t=>({taskId:t.publicId,externalId:t.externalId,name:t.name,type:t.type,scheduleMode:t.scheduleMode,requestedStart:t.requestedStart,start:t.startDate,end:t.endDate,duration:t.duration,progress:t.progress,parentExternalId:t.parentId===null?null:externalById.get(t.parentId)??null,siblingOrder:t.sortOrder}))}
function validSession(session:ReturnType<EditSessionRepository["findById"]>,project:ReturnType<ProjectRepository["findCredentialById"]>,authorization:AuthorizedEditSession,now:Date){if(!session||!project||session.revokedAt!==null)return false;const expiry=Date.parse(session.expiresAt);return session.projectId===project.id&&project.publicId===authorization.projectPublicId&&project.authVersion===authorization.projectAuthVersion&&session.authVersion===project.authVersion&&session.tokenHash.equals(authorization.tokenHash)&&Number.isFinite(expiry)&&expiry>now.getTime()}
export class ProjectCopyService{
 private readonly projects:ProjectRepository;private readonly sessions:EditSessionRepository;private readonly schedules:ScheduleRepository;private readonly clock:()=>Date;private readonly generatePublicId:()=>string;private readonly generateTaskPublicId:()=>string;private readonly generateLinkPublicId:()=>string;private readonly hashPassword:(password:string)=>Promise<PasswordHashRecord>;private readonly generateSessionToken:()=>NewSessionToken;
 constructor(private readonly database:Database.Database,options:ProjectCopyServiceOptions={}){this.projects=new ProjectRepository(database);this.sessions=new EditSessionRepository(database);this.schedules=new ScheduleRepository(database);this.clock=options.clock??(()=>new Date());this.generatePublicId=options.generatePublicId??randomUUID;this.generateTaskPublicId=options.generateTaskPublicId??randomUUID;this.generateLinkPublicId=options.generateLinkPublicId??randomUUID;this.hashPassword=options.hashPassword??hashEditPassword;this.generateSessionToken=options.generateSessionToken??createSessionToken}
 async copy(authorization:AuthorizedEditSession,expectedRevision:number,input:CopyProjectRequest):Promise<CopiedProject>{const password=await this.hashPassword(input.editPassword);const newSession=this.generateSessionToken();for(let attempt=0;attempt<ID_ATTEMPTS;attempt+=1){const newPublicId=this.generatePublicId();if(!isCanonicalUuidV4(newPublicId)||this.projects.findByPublicId(newPublicId))continue;const tx=this.database.transaction(()=>{const now=this.clock(),nowText=now.toISOString();const source=this.projects.findCredentialById(authorization.projectId);const sourceSession=this.sessions.findById(authorization.sessionId);if(!validSession(sourceSession,source,authorization,now))throw new EditSessionInvalidError();if(!source||source.revision!==expectedRevision)throw new RevisionMismatchError();const sourceTasks=this.schedules.listTasks(source.id),sourceLinks=this.schedules.listLinks(source.id),sourceHolidays=this.schedules.listHolidays(source.id);if(sourceTasks.length>MAX_PROJECT_TASKS)throw new PersistedScheduleInvalidError();const calendar=createWorkingCalendar({timezone:"Asia/Seoul",weekendDays:[6,0],holidays:sourceHolidays.map(h=>({date:h.holidayDate,name:h.name}))});recalculatePersistedHierarchy(sourceTasks,calendar);const project=this.projects.insert({publicId:newPublicId,name:input.name,description:input.description,passwordKdf:password.algorithm,passwordSalt:password.salt,passwordHash:password.hash,scryptN:password.n,scryptR:password.r,scryptP:password.p,scryptKeyLength:password.keyLength,calendarTimezone:"Asia/Seoul",createdAt:nowText,updatedAt:nowText});for(const h of sourceHolidays)this.schedules.insertHoliday(project.id,h.holidayDate,h.name,nowText);const newBySourceId=new Map<number,TaskRecord>(),pending=[...sourceTasks];while(pending.length){let inserted=0;for(let i=pending.length-1;i>=0;i-=1){const s=pending[i];if(s.parentId!==null&&!newBySourceId.has(s.parentId))continue;let publicId="";for(let n=0;n<ID_ATTEMPTS;n+=1){const c=this.generateTaskPublicId();if(isCanonicalUuidV4(c)&&!this.schedules.taskPublicIdExists(c)){publicId=c;break}}if(!publicId)throw new Error("Unique task identifier could not be generated.");const t=this.schedules.insertTask({projectId:project.id,externalId:s.externalId,publicId,name:s.name,type:s.type,scheduleMode:s.scheduleMode,requestedStart:s.requestedStart,startDate:s.startDate,endDate:s.endDate,duration:s.duration,progress:input.resetProgress&&s.type!=="summary"?0:s.progress,parentId:s.parentId===null?null:newBySourceId.get(s.parentId)!.id,sortOrder:s.sortOrder,createdAt:nowText,updatedAt:nowText});newBySourceId.set(s.id,t);pending.splice(i,1);inserted+=1}if(inserted===0)throw new PersistedScheduleInvalidError()}
 if(input.resetProgress){const copied=this.schedules.listTasks(project.id),derived=recalculateHierarchy(dtoTasks(copied),calendar);for(const t of derived){if(t.type!=="summary")continue;if(!this.schedules.updateSummarySchedule(project.id,t.taskId,{startDate:t.start,endDate:t.end,duration:t.duration,progress:t.progress,updatedAt:nowText}))throw new PersistedScheduleInvalidError()}}
 for(const l of sourceLinks){const predecessor=newBySourceId.get(l.predecessorTaskId),successor=newBySourceId.get(l.successorTaskId);if(!predecessor||!successor)throw new PersistedScheduleInvalidError();let publicId="";for(let n=0;n<ID_ATTEMPTS;n+=1){const c=this.generateLinkPublicId();if(isCanonicalUuidV4(c)&&!this.schedules.linkPublicIdExists(c)){publicId=c;break}}if(!publicId)throw new Error("Unique link identifier could not be generated.");this.schedules.insertLink({publicId,projectId:project.id,predecessorTaskId:predecessor.id,successorTaskId:successor.id,type:l.type,lag:l.lag,createdAt:nowText,updatedAt:nowText})}
 this.sessions.insert({projectId:project.id,tokenHash:newSession.tokenHash,authVersion:project.authVersion,createdAt:nowText,expiresAt:sessionExpiry(now).toISOString()});const copiedTasks=this.schedules.listTasks(project.id),copiedLinks=this.schedules.listLinks(project.id),externalById=new Map(copiedTasks.map(t=>[t.id,t.externalId]));return{response:{data:{project:{publicId:project.publicId,name:project.name,description:project.description,revision:project.revision,calendar:{timezone:"Asia/Seoul",weekendDays:[6,0],holidays:sourceHolidays.map(h=>({date:h.holidayDate,name:h.name}))}},tasks:dtoTasks(copiedTasks),links:copiedLinks.map(l=>({id:l.publicId,predecessorExternalId:externalById.get(l.predecessorTaskId)!,successorExternalId:externalById.get(l.successorTaskId)!,type:l.type,lag:l.lag})),permission:"edit",operation:{kind:"projectCopy",sourcePublicId:source.publicId,sourceRevision:source.revision,counts:{tasks:copiedTasks.length,links:copiedLinks.length,holidays:sourceHolidays.length}},warnings:[]}},rawSessionToken:newSession.rawToken}});try{return tx.immediate()}catch(error){if(this.projects.findByPublicId(newPublicId))continue;throw error}}throw new Error("A unique project identifier could not be generated.")}
}