import { describe, expect, it } from "vitest";
import type { ProjectImportPreviewDto } from "../../src/contracts/project-import";
import { canCommitImport, importPreviewFrom, importPreviewMatches, importSnapshotFrom } from "../../src/features/projects/project-import-model";
const schedule={requestedStart:"2026-10-06",start:"2026-10-06",end:"2026-10-06",duration:1,progress:0,status:"not_started" as const,baselineStart:null,baselineDuration:null,baselineEnd:null};
const preview:ProjectImportPreviewDto={schemaVersion:"1.1",projectPublicId:"target",baseRevision:9,previewDigest:"a".repeat(64),canCommit:true,sourceProject:{name:"source",description:""},summary:{taskCreates:1,linkCreates:0,explicitMembershipCreates:0},normalizedTasks:[{...schedule,externalId:"T1",sourceTaskId:null,name:"Task",type:"task",parentExternalId:null,description:null,url:null,scheduleMode:"auto",membership:{explicitMilestoneExternalId:null,effectiveMilestoneExternalId:null,inheritedFromExternalId:null}}],changedTasks:[],warnings:[],targetCalendar:{timezone:"Asia/Seoul",weekendDays:[6,0],holidays:[]}};
describe("revision-bound import review",()=>{
 it("accepts complete server projection without issuing target UUIDs",()=>expect(importPreviewFrom({data:preview})).toEqual(preview));
 it.each([{...preview,previewDigest:"wrong"},{...preview,baseRevision:0},{...preview,summary:{...preview.summary,taskCreates:-1}},{...preview,normalizedTasks:[{...preview.normalizedTasks[0],membership:undefined}]}])("fails closed for malformed preview metadata",(data)=>expect(importPreviewFrom({data})).toBeNull());
 it("binds both target and reviewed revision",()=>{expect(importPreviewMatches(preview,"target",9)).toBe(true);expect(importPreviewMatches(preview,"other",9)).toBe(false);expect(importPreviewMatches(preview,"target",10)).toBe(false);});
 it.each([[false,true,false],[true,false,false],[true,true,true]])("requires same File, edit permission and no pending request",(same,editable,pending)=>expect(canCommitImport(preview,"target",9,same,editable,pending)).toBe(false));
 it("requires nonempty committable preview",()=>{expect(canCommitImport(preview,"target",9,true,true,false)).toBe(true);expect(canCommitImport({...preview,canCommit:false},"target",9,true,true,false)).toBe(false);expect(canCommitImport({...preview,summary:{...preview.summary,taskCreates:0}},"target",9,true,true,false)).toBe(false);expect(canCommitImport(null,"target",9,true,true,false)).toBe(false);});
 it("accepts only the same target's single-revision canonical append response",()=>{const response={data:{project:{publicId:"target",revision:10},tasks:[{taskId:"new-uuid",externalId:"T1"}],links:[]}};expect(importSnapshotFrom(response,"target",9)).toEqual(response);expect(importSnapshotFrom(response,"other",9)).toBeNull();expect(importSnapshotFrom(response,"target",8)).toBeNull();expect(importSnapshotFrom({data:{...response.data,tasks:[{}]}},"target",9)).toBeNull();});
});
