import { openMilestoneEditor } from "./helpers/milestone-ui";
import { expect, test, isolatedApplicationOptions } from "./fixtures/isolated-application";
import type { ProjectSnapshotResponse, ProjectTaskDto, TaskMutationResponse } from "../../src/contracts/projects";
import type { MilestoneDashboardResponse } from "../../src/contracts/milestone-dashboard";
import { chooseTaskInformation } from "./helpers/task-context-menu";

const adminPassword = "Stage463SyntheticAdmin!";
test.use({ ...isolatedApplicationOptions, isolatedResourceAdminPassword: adminPassword, viewport: { width: 1440, height: 900 } });

test("#463 실제 SQLite Editor→Grid→단계 KPI·공수·물류·Resource drill과 readonly peer 보존", async ({ page, baseURL, browser }, testInfo) => {
  test.setTimeout(240_000);
  page.setDefaultTimeout(20_000);
  const origin = baseURL!;
  const created = await page.request.post("/api/projects", { headers: { Origin: origin }, data: { name: "Stage Dashboard #463", ownerName: "E2E 자동화", description: "실제 SQLite 단계 범위", editPassword: "Stage463!" } });
  expect(created.status()).toBe(201);
  const publicId = (await created.json()).data.project.publicId as string, api = `/api/projects/${publicId}`;
  const get = async () => (await (await page.request.get(api)).json()) as ProjectSnapshotResponse;
  let snapshot = await get();
  const headers = () => ({ Origin: origin, "If-Match": `"${snapshot.data.project.revision}"` });
  const mutate = async (path: string, data: unknown, method: "post" | "put" | "patch" = "post", status = 200) => {
    const response = await page.request[method](`${api}${path}`, { headers: headers(), data });
    expect(response.status(), `${method} ${path}: ${await response.text()}`).toBe(status);
    snapshot = await get();
    return response;
  };
  const add = async (name: string, type: ProjectTaskDto["type"], externalId: string, parentTaskId?: string, duration = 2) => {
    const response = await mutate("/tasks", { name, type, externalId, parentTaskId, ...(type === "summary" ? {} : { start: "2026-10-05", duration: type === "milestone" ? 0 : duration, progress: 0 }) }, "post", 201);
    return (await response.json() as TaskMutationResponse).data.tasks.find((task) => task.externalId === externalId)!;
  };
  const a = await add("동명 병렬 단계", "milestone", "M-A"), b = await add("동명 병렬 단계", "milestone", "M-B"), join = await add("병렬 합류 단계", "milestone", "M-JOIN");
  const manual = await add("수동 이벤트", "milestone", "M-MANUAL"), completed = await add("완료 기록 이벤트", "milestone", "M-COMPLETED");
  const summary = await add("상속 Summary", "summary", "S"), child = await add("상속 일반 작업", "task", "CHILD", summary.taskId, 10), override = await add("직접 override 완료 작업", "task", "OVERRIDE", summary.taskId);
  const empty = await add("빈 Summary", "summary", "EMPTY"), direct = await add("직접 지정 작업", "task", "DIRECT"), free = await add("미지정 공수 작업", "task", "FREE");
  await mutate("/milestone-memberships", { changes: [{ taskId: summary.taskId, milestoneTaskId: a.taskId }, { taskId: override.taskId, milestoneTaskId: b.taskId }, { taskId: empty.taskId, milestoneTaskId: a.taskId }, { taskId: direct.taskId, milestoneTaskId: a.taskId }] });
  await mutate(`/tasks/${override.taskId}`, { status: "completed" }, "patch");
  await mutate(`/tasks/${completed.taskId}`, { status: "completed" }, "patch");
  for (const predecessor of [a, b]) await mutate("/links", { predecessorExternalId: predecessor.externalId, successorExternalId: join.externalId, type: "FS", lag: 0 }, "post", 201);

  expect((await page.request.post("/api/resource-catalog/admin-sessions", { headers: { Origin: origin }, data: { password: adminPassword } })).status()).toBe(201);
  let catalog = (await (await page.request.get("/api/resources")).json()).data;
  const resourceResponse = await page.request.post("/api/resources", { headers: { Origin: origin, "If-Match": `"${catalog.revision}"` }, data: { name: "개인 개발자", developerGrade: "ADVANCED", roles: ["DEVELOPER"] } });
  expect(resourceResponse.status()).toBe(201); catalog = (await resourceResponse.json()).data;
  const resourceId = catalog.resources[0].id as string;
  const groupResponse = await page.request.post("/api/resource-groups", { headers: { Origin: origin, "If-Match": `"${catalog.revision}"` }, data: { name: "참조 그룹" } });
  expect(groupResponse.status()).toBe(201); catalog = (await groupResponse.json()).data;
  const groupId = catalog.groups[0].id as string;
  for (const [task, percent] of [[child, 50], [override, 100], [free, 50]] as const) await mutate(`/tasks/${task.taskId}/assignments`, { catalogRevision: catalog.revision, targets: [{ kind: "resource", id: resourceId, allocation: { start: null, end: null, percent } }] }, "put");
  await mutate(`/tasks/${summary.taskId}/assignments`, { catalogRevision: catalog.revision, targets: [{ kind: "group", id: groupId }] }, "put");
  const processResponse = await mutate("/logistics/processes", { name: "연결 공정", code: "PROC-463" }, "post", 201);
  const processId = (await processResponse.json()).data.logistics.processes.find((row: { code: string }) => row.code === "PROC-463").id as string;
  const equipmentResponse = await mutate("/logistics/equipment", { name: "연결 설비", code: "EQ-463", processId, equipmentType: "stocker", managementUnit: "unit", quantity: 1 }, "post", 201);
  const equipmentId = (await equipmentResponse.json()).data.logistics.equipment.find((row: { code: string }) => row.code === "EQ-463").id as string;
  await mutate(`/tasks/${override.taskId}/logistics-links`, { equipmentLinks: [{ equipmentId, scope: "self" }], systemLinks: [] }, "put");
  const dashboard = async (query = "") => {
    const response = await page.request.get(`${api}/milestone-dashboard${query}`); expect(response.status()).toBe(200);
    return (await response.json() as MilestoneDashboardResponse).data;
  };
  // Compile read routes before measuring browser instance preservation in Next dev.
  await dashboard();
  for (const path of ["/assigned-targets", "/resource-workload", "/logistics/dashboard", `/tasks/${child.taskId}/assignments`, `/tasks/${child.taskId}/logistics-links`]) await (await page.request.get(`${api}${path}`)).body();
  await page.goto(`/projects/${publicId}`);
  await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
  const row = (taskId: string) => page.locator(`.wx-table-container .wx-row[data-id=":${taskId}"]`).first();
  await row(child.taskId).click({ button: "right" }); await chooseTaskInformation(page);
  const dialog = page.getByRole("dialog", { name: "작업 정보", exact: true });
  await expect(dialog).toContainText("상속 Summary에서 상속");
  const picker = dialog.getByRole("combobox", { name: "완료 단계", exact: true });
  await picker.fill(join.taskId); await picker.press("Enter");
  const beforeRevision = snapshot.data.project.revision;
  await dialog.getByRole("button", { name: "저장", exact: true }).click(); await expect(dialog).toHaveCount(0);
  snapshot = await get(); expect(snapshot.data.project.revision).toBe(beforeRevision + 1);
  expect(snapshot.data.tasks.find((task) => task.taskId === child.taskId)?.membership).toMatchObject({ explicitMilestoneTaskId: join.taskId, effectiveMilestoneTaskId: join.taskId });
  await openMilestoneEditor(page, join.taskId);
  await dialog.getByRole("tab", { name: /소속 작업/ }).click(); await expect(dialog).toContainText("유효 일반 작업 1개"); await expect(dialog).toContainText("상속 일반 작업");
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click();
  await page.getByRole("tab", { name: "일정", exact: true }).click();
  const gridHeader = page.locator(".wx-table-container .wx-header").first();
  await gridHeader.click({ button: "right" }); await page.locator(".project-column-menu").getByRole("checkbox", { name: "완료 단계", exact: true }).check(); await page.keyboard.press("Escape");
  await expect(row(child.taskId).getByRole("button", { name: /완료 단계:/ })).toContainText(join.name);
  const stageTrigger = page.locator("#project-panel-schedule .project-stage-filter-trigger");
  await stageTrigger.click(); const stageSearch = page.getByRole("combobox", { name: "단계 이름·외부 ID·작업 ID 검색" }); await stageSearch.fill(join.taskId); await stageSearch.press("End"); await stageSearch.press("Enter");
  await expect(row(child.taskId)).toBeVisible(); await expect(row(free.taskId)).toHaveCount(0);
  await stageTrigger.click(); await page.getByRole("combobox", { name: "단계 이름·외부 ID·작업 ID 검색" }).press("Home"); await page.keyboard.press("Enter");
  const full = await dashboard("?asOfDate=2026-10-06&mdPerMm=null");
  expect(full.projectRevision).toBe(snapshot.data.project.revision);
  const fullJoin = full.rows.find((stage) => stage.milestoneTaskId === join.taskId)!;
  expect(fullJoin.stageGate.memberTaskIds).toEqual([child.taskId]);
  expect([...fullJoin.stageGate.incompletePredecessorMilestoneTaskIds].sort()).toEqual([a.taskId, b.taskId].sort());
  expect(fullJoin.stageGate.ready).toBe(false); expect(fullJoin.riskTaskIds).toEqual([child.taskId]);
  expect(full.kpi.ready.milestoneTaskIds).toContain(b.taskId); expect(full.kpi.blocked.milestoneTaskIds).toContain(join.taskId); expect(full.kpi.atRisk.milestoneTaskIds).toContain(join.taskId);
  expect(full.kpi.completion).toMatchObject({ numerator: 1, denominator: 5 });
  expect(full.rows.find((stage) => stage.milestoneTaskId === manual.taskId)?.stageGate).toMatchObject({ manualEvent: true, ready: null });
  expect(full.effort.buckets.find((bucket) => bucket.milestoneTaskId === null)?.taskIds).toContain(free.taskId);
  expect(full.effort.assignmentIds).toHaveLength(3); expect(full.effort.plannedMd).toBe(full.effort.buckets.reduce((sum, bucket) => sum + bucket.plannedMd, 0));
  const partial = await dashboard(`?milestoneIds=${join.taskId}&from=2026-10-05&to=2026-10-06&mdPerMm=null`);
  expect(partial.rows).toHaveLength(1); expect(partial.rows[0].stageGate).toEqual(fullJoin.stageGate);
  // Project's default Korean calendar excludes the 2026-10-05 observed holiday.
  expect(partial.effort.plannedMd).toBe(2); expect(partial.rows[0].effort.plannedMd).toBe(0.5);
  expect(partial.effort.assignments.every((assignment) => assignment.effectiveWorkingDays === 1)).toBe(true);
  expect(partial.effort.buckets.find((bucket) => bucket.milestoneTaskId === null)?.plannedMd).toBe(0.5);
  const logistics = (await (await page.request.get(`${api}/logistics/dashboard?equipmentIds=${equipmentId}&from=2026-10-05&to=2026-10-06&mdPerMm=null`)).json()).data;
  expect(logistics.milestoneStages.milestoneTaskIds).toEqual([b.taskId]);
  expect(logistics.milestoneStages.rows[0].stageGate).toEqual(full.rows.find((stage) => stage.milestoneTaskId === b.taskId)!.stageGate);
  await page.getByRole("tab", { name: "Milestone 대시보드", exact: true }).click();
  const panel = page.getByTestId("milestone-dashboard"); await expect(panel).toHaveAttribute("data-ready", "true");
  await panel.getByText("단계 표시·공수 범위 조건", { exact: true }).click();
  await panel.getByLabel("공수 시작일", { exact: true }).fill("2026-10-05"); await panel.getByLabel("공수 종료일", { exact: true }).fill("2026-10-06");
  await panel.getByRole("combobox", { name: "M/M 환산 기준", exact: true }).selectOption("unset"); await expect(panel).toHaveAttribute("data-ready", "true");
  await expect(panel).toContainText("2 M/D");
  // #528 uses the exact-assignment readonly POST, not the legacy workload GET.
  const drillRequest = page.waitForRequest((request) => request.method() === "POST" && request.url().includes(`${api}/resource-dashboard/query`) && request.postData()?.includes('"exactAssignments"') === true);
  await panel.getByRole("button", { name: "해당 범위 리소스 보기", exact: true }).click();
  const requestPayload = (await drillRequest).postDataJSON();
  expect([...requestPayload.scope.assignmentIds].sort()).toEqual([...partial.effort.assignmentIds].sort());
  expect(requestPayload.filters).toMatchObject({ from: "2026-10-05", to: "2026-10-06" });
  const resources = page.getByRole("tabpanel", { name: "리소스", exact: true });
  await expect(page.getByRole("region", { name: "임시 조회 범위", exact: true })).toContainText("Milestone 원본의 정확한 배정 범위");
  await expect(resources).toContainText("2.00");
  await page.getByRole("tab", { name: "물류 구성", exact: true }).click();
  await page.getByRole("tab", { name: "KPI 대시보드", exact: true }).click();
  const logisticsPanel = page.getByRole("tabpanel", { name: "물류 구성", exact: true });
  await expect(logisticsPanel.getByRole("heading", { name: "관련 단계 — 단계 전체 상태 기준", exact: true })).toBeVisible();
  const relatedStage = logisticsPanel.getByRole("region", { name: "완료 단계 전체 상태 표 가로 스크롤", exact: true }).getByRole("row", { name: /M-B/ });
  await expect(relatedStage).toContainText("Ready"); await expect(relatedStage).toContainText("1 / 1");
  expect((await get()).data.project.revision).toBe(snapshot.data.project.revision);
  await testInfo.attach("actual-canonical-stage-snapshot", { body: JSON.stringify({ projectPublicId: publicId, projectRevision: full.projectRevision, catalogRevision: full.catalogRevision, stageIds: full.rows.map((stage) => stage.milestoneTaskId), assignmentIds: partial.effort.assignmentIds, workloadRange: partial.workloadRange, fullJoin: fullJoin.stageGate, grandTotalMd: partial.effort.plannedMd, bucketTotals: partial.effort.buckets.map((bucket) => ({ milestoneTaskId: bucket.milestoneTaskId, plannedMd: bucket.plannedMd })) }, null, 2), contentType: "application/json" });

  const readonly = await browser.newContext({ baseURL: origin, viewport: { width: 1440, height: 900 } });
  try {
    const peer = await readonly.newPage(); await peer.goto(`/projects/${publicId}`);
    await expect(peer.getByText("읽기 전용", { exact: true }).first()).toBeVisible();
    const unauthorized = await readonly.request.post(`${api}/milestone-memberships`, { headers: headers(), data: { changes: [{ taskId: child.taskId, milestoneTaskId: null }] } }); expect(unauthorized.status()).toBe(401);
    const frame = peer.locator(".project-gantt-frame"); await expect(frame).toHaveAttribute("data-project-gantt-api-instance", /.+/);
    const instance = await frame.getAttribute("data-project-gantt-api-instance");
    await peer.getByRole("button", { name: "주", exact: true }).click();
    const treeToggle = peer.locator(`.wx-table-container .wx-row[data-id=":${summary.taskId}"] [data-action="open-task"]`).first();
    await treeToggle.click(); await expect(treeToggle).toHaveClass(/wxi-menu-right/);
    const peerHeader = peer.locator(".wx-table-container .wx-header").first();
    await peerHeader.click({ button: "right" }); await peer.locator(".project-column-menu").getByRole("checkbox", { name: "완료 단계", exact: true }).check(); await peer.keyboard.press("Escape");
    const nameWidth = (await peerHeader.locator('[data-header-id=":text"]').boundingBox())!.width;
    const selected = peer.locator(`.wx-table-container .wx-row[data-id=":${free.taskId}"]`).first(); await selected.locator('[data-col-id=":text"]').click(); await expect(selected).toHaveClass(/wx-selected/);
    const chart = peer.locator(".project-gantt-widget .wx-chart"); await chart.evaluate((element) => { element.scrollLeft = 120; }); const scroll = await chart.evaluate((element) => element.scrollLeft);
    expect(scroll).toBeGreaterThan(0);
    const liveViewport = () => frame.evaluate((element) => {
      const owner = element as HTMLElement & { readonly __masterganttPublicViewport?: { left: number; top: number } };
      return { domLeft: element.querySelector(".wx-chart")!.scrollLeft, publicLeft: owner.__masterganttPublicViewport?.left, publicTop: owner.__masterganttPublicViewport?.top };
    });
    await expect.poll(liveViewport).toMatchObject({ domLeft: scroll, publicLeft: scroll });
    const scrollCheckpoint = async (phase: string) => ({ phase, ...(await chart.evaluate((element) => ({ scrollLeft: element.scrollLeft, scrollWidth: element.scrollWidth, clientWidth: element.clientWidth, maximum: element.scrollWidth - element.clientWidth, gridWidth: element.closest(".project-gantt-frame")!.querySelector(".wx-table-container")!.getBoundingClientRect().width, fullscreen: Boolean(document.fullscreenElement), viewport: innerWidth }))), ...(await liveViewport()) });
    const scrollCheckpoints = [await scrollCheckpoint("before-fullscreen")];
    await peer.getByRole("button", { name: "Gantt 전체 화면", exact: true }).click();
    await expect.poll(() => peer.evaluate(() => Boolean(document.fullscreenElement))).toBe(true);
    scrollCheckpoints.push(await scrollCheckpoint("fullscreen-active"));
    await peer.getByRole("button", { name: "Gantt 전체 화면 종료", exact: true }).click();
    await expect.poll(() => peer.evaluate(() => Boolean(document.fullscreenElement))).toBe(false);
    await expect.poll(liveViewport).toMatchObject({ domLeft: scroll, publicLeft: scroll });
    scrollCheckpoints.push(await scrollCheckpoint("after-fullscreen-exit"));
    scrollCheckpoints.push(await scrollCheckpoint("before-peer-hide"));
    await peer.getByRole("tab", { name: "Milestone 대시보드", exact: true }).click(); await expect(peer.getByTestId("milestone-dashboard")).toHaveAttribute("data-ready", "true");
    await testInfo.attach("actual-readonly-dashboard", { body: await peer.screenshot(), contentType: "image/png" });
    await peer.getByRole("tab", { name: "일정", exact: true }).click();
    await expect.poll(async () => JSON.parse(await frame.getAttribute("data-gantt-peer-restore") ?? "{}")).toMatchObject({ requestedLeft: scroll, count: 1 });
    try {
      await expect.poll(liveViewport).toMatchObject({ domLeft: scroll, publicLeft: scroll });
    } finally {
      await testInfo.attach("actual-peer-live-state", { body: JSON.stringify({ viewport: await liveViewport(), peerRestore: JSON.parse(await frame.getAttribute("data-gantt-peer-restore") ?? "{}"), events: JSON.parse(await frame.getAttribute("data-gantt-public-scroll-events") ?? "[]") }, null, 2), contentType: "application/json" });
    }
    await peer.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    scrollCheckpoints.push(await scrollCheckpoint("after-peer-return"));
    await peer.setViewportSize({ width: 1456, height: 900 }); await peer.setViewportSize({ width: 1440, height: 900 });
    await peer.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
    await expect.poll(liveViewport).toMatchObject({ domLeft: scroll, publicLeft: scroll });
    scrollCheckpoints.push(await scrollCheckpoint("after-followup-layout"));
    await testInfo.attach("actual-scroll-checkpoints", { body: JSON.stringify(scrollCheckpoints, null, 2), contentType: "application/json" });
    await testInfo.attach("actual-public-scroll-state", { body: JSON.stringify({ peerRestore: JSON.parse(await frame.getAttribute("data-gantt-peer-restore") ?? "{}"), scrollEvents: JSON.parse(await frame.getAttribute("data-gantt-public-scroll-events") ?? "[]") }, null, 2), contentType: "application/json" });
    await testInfo.attach("actual-stage-dashboard", { body: JSON.stringify({ projectRevision: full.projectRevision, catalogRevision: full.catalogRevision, stageIds: full.rows.map((stage) => stage.milestoneTaskId), assignmentIds: partial.effort.assignmentIds, fullJoin: fullJoin.stageGate, grandTotalMd: partial.effort.plannedMd, readonlyApiInstance: instance, scroll, nativeFullscreenPeerSwitch: "NOT TESTED: peer tabs are outside fullscreen owner; exit then switch" }, null, 2), contentType: "application/json" });
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-fullscreen-exit")!.scrollLeft, "Native fullscreen exit preserves scroll").toBe(scroll);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-peer-return")!.gridWidth, "Peer return preserves Grid split width").toBeCloseTo(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "before-peer-hide")!.gridWidth, 0);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-peer-return")!.clientWidth, "Peer return preserves Chart split width").toBe(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "before-peer-hide")!.clientWidth);
    await expect(frame).toHaveAttribute("data-project-gantt-api-instance", instance!); await expect(frame).toHaveAttribute("data-gantt-scale-mode", "week"); await expect(selected).toHaveClass(/wx-selected/);
    await expect(treeToggle).toHaveClass(/wxi-menu-right/); await expect(peerHeader.getByText("완료 단계", { exact: true })).toBeVisible();
    expect((await peerHeader.locator('[data-header-id=":text"]').boundingBox())!.width).toBeCloseTo(nameWidth, 0);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-peer-return")!.scrollLeft, "Dashboard/Gantt peer return preserves scroll").toBe(scroll);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-followup-layout")!.scrollLeft, "Followup layout preserves restored scroll").toBe(scroll);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-peer-return")!.publicLeft).toBe(scroll);
    expect(scrollCheckpoints.find((checkpoint) => checkpoint.phase === "after-followup-layout")!.publicLeft).toBe(scroll);
    expect(JSON.parse(await frame.getAttribute("data-gantt-peer-restore") ?? "{}").count).toBe(1);
  } finally { await readonly.close(); }
  expect((await get()).data.project.revision).toBe(snapshot.data.project.revision);
});
