import { openMilestoneEditor } from "./helpers/milestone-ui";
import { mkdir, writeFile } from "node:fs/promises";
import { expect, test, isolatedApplicationOptions } from "./fixtures/isolated-application";
import type { ProjectSnapshotResponse, ProjectTaskDto, TaskMutationResponse } from "../../src/contracts/projects";
import { chooseTaskInformation } from "./helpers/task-context-menu";

test.use(isolatedApplicationOptions);

test("#461 실제 SQLite Editor 원자 저장·상속·양쪽 canonical·재개·geometry", async ({ page, baseURL }) => {
  test.setTimeout(180_000);
  const origin = baseURL!;
  const created = await page.request.post("/api/projects", { headers: { Origin: origin }, data: { name: "Stage Editor #461", description: "실제 SQLite Editor", ownerName: "E2E 자동화", editPassword: "Stage461!" } });
  expect(created.status()).toBe(201);
  const publicId = (await created.json()).data.project.publicId as string;
  const api = `/api/projects/${publicId}`;
  const get = async () => (await (await page.request.get(api)).json()) as ProjectSnapshotResponse;
  let snapshot = await get();
  const headers = () => ({ Origin: origin, "If-Match": `"${snapshot.data.project.revision}"` });
  const add = async (name: string, type: ProjectTaskDto["type"], parentTaskId?: string) => {
    const response = await page.request.post(`${api}/tasks`, { headers: headers(), data: type === "summary" ? { name, type, parentTaskId } : { name, type, start: "2026-10-05", duration: type === "milestone" ? 0 : 2, progress: 0, parentTaskId } });
    expect(response.status()).toBe(201); const value = await response.json() as TaskMutationResponse; snapshot = { data: { ...value.data, permission: "edit" } }; return value.data.tasks.filter((task) => task.name === name).at(-1)!;
  };
  const m1 = await add("설계 완료 단계 긴 한글 English milestone alpha", "milestone"), m2 = await add("설계 완료 단계 긴 한글 English milestone alpha", "milestone");
  const summary = await add("Summary 기본 단계", "summary"), child = await add("Inherited child", "task", summary.taskId), override = await add("Override child", "task", summary.taskId);
  for (let index = 0; index < 18; index++) await add(`미지정 후보 ${index} 긴 한글 English extraordinary task identity`, "task");
  const assign = await page.request.post(`${api}/milestone-memberships`, { headers: headers(), data: { changes: [{ taskId: summary.taskId, milestoneTaskId: m1.taskId }, { taskId: override.taskId, milestoneTaskId: m2.taskId }] } });
  expect(assign.status()).toBe(200); snapshot = await get();
  const dependency = await page.request.post(`${api}/links`, { headers: headers(), data: { predecessorExternalId: m1.externalId, successorExternalId: m2.externalId, type: "FS", lag: 0 } }); expect(dependency.status()).toBe(201); snapshot = await get();
  await page.setViewportSize({ width: 1440, height: 844 });
  await page.goto(`/projects/${publicId}`);
  await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
  const frame = page.locator(".project-gantt-frame"), instance = await frame.getAttribute("data-project-gantt-instance");
  const dialog = page.getByRole("dialog", { name: "작업 정보", exact: true });
  const open = async (taskId: string) => {
    if (snapshot.data.tasks.find(task => task.taskId === taskId)?.type === "milestone") { await openMilestoneEditor(page, taskId); return; }
    await page.getByRole("tab", { name: "일정", exact: true }).click();
    const row = page.locator(`.project-gantt-widget .wx-table-container .wx-row[data-id=":${taskId}"]`).first();
    await row.click({ button: "right" }); await chooseTaskInformation(page); await expect(dialog).toBeVisible();
  };
  await open(child.taskId);
  await expect(dialog).toContainText("Summary 기본 단계에서 상속");
  const picker = dialog.getByRole("combobox", { name: "완료 단계", exact: true });
  await picker.fill(`  ${m2.taskId.toUpperCase()}  `);
  await expect(dialog.getByRole("listbox").getByRole("option")).toHaveCount(1);
  await picker.press("Enter");
  await dialog.getByLabel("작업명", { exact: true }).fill("Child renamed and assigned");
  let patches = 0, batches = 0;
  page.on("request", (request) => { if (request.method() === "PATCH" && request.url().endsWith(`/tasks/${child.taskId}`)) patches++; if (request.method() === "POST" && request.url().endsWith("/milestone-memberships")) batches++; });
  const before = snapshot.data.project.revision;
  await dialog.getByRole("button", { name: "저장", exact: true }).click();
  await expect(dialog).toHaveCount(0); snapshot = await get();
  expect(snapshot.data.project.revision).toBe(before + 1); expect(patches).toBe(1);
  expect(snapshot.data.tasks.find((row) => row.taskId === child.taskId)).toMatchObject({ name: "Child renamed and assigned", membership: { explicitMilestoneTaskId: m2.taskId, effectiveMilestoneTaskId: m2.taskId } });
  await open(m2.taskId);
  await dialog.getByRole("tab", { name: /소속 작업/ }).click();
  await expect(dialog).toContainText("유효 일반 작업 2개");
  await dialog.getByRole("combobox", { name: "소속 상태", exact: true }).selectOption("all");
  const summaryRow = dialog.getByRole("row", { name: /Summary 기본 단계/ });
  await summaryRow.getByRole("button", { name: "이 단계로 이동", exact: true }).click();
  await expect(dialog).toContainText("유효 일반 작업 영향 0개");
  await dialog.getByRole("tab", { name: "작업 정보", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "저장", exact: true })).toBeDisabled();
  await dialog.getByRole("tab", { name: /소속 작업/ }).click();
  const batchBefore = snapshot.data.project.revision;
  await dialog.getByRole("button", { name: "소속 변경 적용", exact: true }).click();
  await expect(dialog).toContainText(`Revision ${batchBefore + 1}`); snapshot = await get();
  expect(batches).toBe(1); expect(snapshot.data.project.revision).toBe(batchBefore + 1);
  expect(snapshot.data.tasks.find((row) => row.taskId === override.taskId)?.membership?.explicitMilestoneTaskId).toBe(m2.taskId);
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click();
  await open(summary.taskId);
  await expect(dialog.getByLabel("요청 시작일", { exact: true })).toHaveAttribute("readonly", "");
  await expect(dialog.getByLabel("작업명", { exact: true })).not.toHaveAttribute("readonly", "");
  await expect(dialog).toContainText("직접 지정");
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click();
  await open(m2.taskId);
  await dialog.getByLabel("상태", { exact: true }).selectOption("completed");
  await dialog.getByRole("button", { name: "저장", exact: true }).click();
  await expect(dialog).toContainText("완료 조건");
  snapshot = await get(); const rollback = snapshot;
  const refused = await page.request.post(`${api}/milestone-memberships`, { headers: headers(), data: { changes: [{ taskId: summary.taskId, milestoneTaskId: m1.taskId }, { taskId: m1.taskId, milestoneTaskId: m2.taskId }] } });
  expect(refused.status()).toBe(409); expect(await get()).toEqual(rollback);
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click();
  await dialog.getByRole("button", { name: "변경사항 버리고 닫기", exact: true }).click();
  for (const member of [child, override]) { const response = await page.request.patch(`${api}/tasks/${member.taskId}`, { headers: headers(), data: { status: "completed" } }); expect(response.status()).toBe(200); snapshot = await get(); }
  await page.reload(); await open(m2.taskId);
  const currentInstance = await frame.getAttribute("data-project-gantt-instance");
  await expect(dialog).toContainText("소속 작업 진척 100%");
  await expect(dialog).toContainText("미완료 선행 단계 1개");
  await dialog.getByLabel("상태", { exact: true }).selectOption("completed"); await dialog.getByRole("button", { name: "저장", exact: true }).click();
  await expect(dialog).toContainText("완료 조건");
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click(); await dialog.getByRole("button", { name: "변경사항 버리고 닫기", exact: true }).click();
  await open(m1.taskId); await expect(dialog).toContainText("수동 이벤트 · 작업 진척 대상 없음 (N/A)");
  await dialog.getByLabel("상태", { exact: true }).selectOption("completed"); await dialog.getByRole("button", { name: "저장", exact: true }).click(); await expect(dialog).toContainText("본인 상태: 완료");
  await dialog.getByRole("button", { name: "작업 편집기 닫기", exact: true }).click(); await open(m2.taskId);
  await expect(dialog).toContainText("완료 처리 가능");
  await dialog.getByLabel("상태", { exact: true }).selectOption("completed"); await dialog.getByRole("button", { name: "저장", exact: true }).click();
  await expect(dialog).toContainText("본인 상태: 완료");
  await dialog.getByRole("tab", { name: /소속 작업/ }).click();
  await expect(dialog.getByRole("button", { name: "소속 변경 적용", exact: true })).toBeDisabled();
  await dialog.getByRole("tab", { name: "작업 정보", exact: true }).click();
  await dialog.getByLabel("상태", { exact: true }).selectOption("in_progress"); await dialog.getByRole("button", { name: "저장", exact: true }).click();
  await expect(dialog).toContainText("본인 상태: 진행 중");
  await dialog.getByRole("tab", { name: /소속 작업/ }).click();
  await dialog.getByRole("combobox", { name: "소속 상태", exact: true }).selectOption("all");
  const metrics = [];
  await mkdir("output/playwright/issue-461", { recursive: true });
  for (const width of [390, 768, 1024, 1440, 1920]) {
    await page.setViewportSize({ width, height: 844 });
    const tab = dialog.getByRole("tab", { name: /소속 작업/ }); await tab.focus(); await tab.press("End"); await expect(dialog.getByRole("tab", { name: /물류 연결/ })).toBeFocused();
    await dialog.getByRole("tab", { name: /물류 연결/ }).press("Home"); await expect(dialog.getByRole("tab", { name: "작업 정보", exact: true })).toBeFocused();
    await dialog.getByRole("tab", { name: "작업 정보", exact: true }).press("ArrowRight"); await expect(tab).toBeFocused();
    const measure = await dialog.evaluate((element) => { const bounds = element.getBoundingClientRect(); const table = element.querySelector("table")!; const scroll = table.parentElement!; const tabs = element.querySelector<HTMLElement>('[role="tablist"]')!, selectedTab = element.querySelector<HTMLElement>('[role="tab"][aria-selected="true"]')!, tabBounds = selectedTab.getBoundingClientRect(), ownerBounds = tabs.getBoundingClientRect(), tabStyle = getComputedStyle(selectedTab), outset = Math.max(0, parseFloat(tabStyle.outlineWidth) + parseFloat(tabStyle.outlineOffset)); const headers = Array.from(table.querySelectorAll("thead th"), (cell) => cell.getBoundingClientRect()); const cells = Array.from(table.querySelectorAll("tbody tr:first-child td"), (cell) => cell.getBoundingClientRect()); const control = table.querySelector<HTMLElement>("tbody tr:first-child td button")!.getBoundingClientRect(); const allControls = Array.from(table.querySelectorAll<HTMLButtonElement>("tbody td button"), (button) => { const control = button.getBoundingClientRect(), cell = button.closest("td")!.getBoundingClientRect(); return { control: { left: control.left, right: control.right, top: control.top, bottom: control.bottom }, cell: { left: cell.left, right: cell.right, top: cell.top, bottom: cell.bottom }, column: button.closest("td")!.cellIndex }; }); const filterControls = Array.from(element.querySelectorAll<HTMLInputElement | HTMLSelectElement>('#task-editor-panel-memberships input, #task-editor-panel-memberships select'), (control) => control.getBoundingClientRect()); return { documentWidth: document.documentElement.scrollWidth, viewport: innerWidth, dialogWidth: bounds.width, tableWidth: table.getBoundingClientRect().width, tableScrollWidth: scroll.scrollWidth, tableClientWidth: scroll.clientWidth, tableColumnsAligned: headers.every((header, index) => Math.abs(header.left - cells[index].left) <= 1 && Math.abs(header.width - cells[index].width) <= 1), siblingCellsNonOverlapping: cells.every((cell, index) => index === 0 || cells[index - 1].right <= cell.left + 1), firstControlContainedInCell: control.left >= cells[0].left && control.right <= cells[0].right, allControlsContainedInCells: allControls.every(({ control, cell }) => control.left >= cell.left && control.right <= cell.right && control.top >= cell.top && control.bottom <= cell.bottom), allSiblingControlsNonOverlapping: allControls.every(({ control }, index) => allControls.slice(index + 1).every(({ control: other }) => control.right <= other.left || other.right <= control.left || control.bottom <= other.top || other.bottom <= control.top)), commandControlCount: allControls.filter(({ column }) => column === 5).length, allControlBounds: allControls, filterControlsNonOverlapping: filterControls.every((control, index) => index === 0 || control.top >= filterControls[index - 1].bottom || control.left >= filterControls[index - 1].right), tabsScrollHeight: tabs.scrollHeight, tabsClientHeight: tabs.clientHeight, focusedTabOutlineVisible: tabBounds.left - outset >= ownerBounds.left && tabBounds.right + outset <= ownerBounds.right && tabBounds.top - outset >= ownerBounds.top && tabBounds.bottom + outset <= ownerBounds.bottom, tabVisible: (() => { const selected = element.querySelector('[role="tab"][aria-selected="true"]')!.getBoundingClientRect(); return selected.left >= bounds.left && selected.right <= bounds.right; })() }; });
    expect(measure.documentWidth).toBeLessThanOrEqual(width); expect(measure.tableWidth).toBeGreaterThanOrEqual(960); expect(measure.tabVisible).toBe(true); expect(measure.tableColumnsAligned).toBe(true); expect(measure.siblingCellsNonOverlapping).toBe(true); expect(measure.firstControlContainedInCell).toBe(true); expect(measure.allControlsContainedInCells).toBe(true); expect(measure.allSiblingControlsNonOverlapping).toBe(true); expect(measure.commandControlCount).toBeGreaterThan(0); expect(measure.filterControlsNonOverlapping).toBe(true); expect(measure.tabsScrollHeight).toBeLessThanOrEqual(measure.tabsClientHeight + 1); expect(measure.focusedTabOutlineVisible).toBe(true); metrics.push({ width, ...measure });
    await page.screenshot({ path: `output/playwright/issue-461/memberships-${width}.png` });
  }
  await writeFile("output/playwright/issue-461/geometry.json", JSON.stringify(metrics, null, 2));
  // Browser reload above creates the expected new instance; dialog save/tab changes preserve it thereafter.
  expect(instance).toBeTruthy();
  await expect(frame).toHaveAttribute("data-project-gantt-instance", currentInstance!);
});
