import { expect, test, type Frame, type Request } from "@playwright/test";
import { submitProjectUnlock } from "./fixtures/isolated-application";
import { deferred, expectSameGanttRoot, ganttRoot, installStatefulProjectFixture, publicId, rememberGanttRoot, rootAdd, rowNamed, taskPath, waitForAnimationFrame, type PostOutcome } from "../fixtures/stateful-project";

test.describe("Issue #3 stable Gantt instance", () => {
  test.use({ viewport: { width: 1440, height: 1200 } });
  test("keeps the instance and supported UI state through a delayed add and ten sequential adds", async ({ page }) => {
    await page.clock.setFixedTime(new Date("2026-09-16T12:00:00.000Z"));
    const fixture = await installStatefulProjectFixture(page);
    await page.goto(`/projects/${publicId}`);
    await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
    await expect(rootAdd(page)).toBeVisible();
    const documentRequests: string[] = [];
    const navigations: string[] = [];
    const recordDocument = (request: Request) => { if (request.resourceType() === "document") documentRequests.push(request.url()); };
    const recordNavigation = (frame: Frame) => { if (frame === page.mainFrame()) navigations.push(frame.url()); };
    page.on("request", recordDocument); page.on("framenavigated", recordNavigation);
    const identity = await rememberGanttRoot(page);
    const summaryRow = rowNamed(page, "Stable summary");
    const summaryToggle = summaryRow.locator('[data-action="open-task"]');
    await expect(summaryToggle).toHaveClass(/wxi-menu-down/);
    await summaryToggle.click(); await expect(summaryToggle).toHaveClass(/wxi-menu-right/);
    await expect(page.getByRole("grid").getByText("Existing summary child", { exact: true })).toHaveCount(0);
    const selectedRow = rowNamed(page, "Stable leaf");
    await selectedRow.locator('[role="gridcell"][data-col-id=":projectStart"]').click();
    await expect(selectedRow).toHaveClass(/wx-selected/);
    const gridHeader = page.locator(".project-gantt-widget .wx-table-container .wx-header").first();
    await gridHeader.click({ button: "right" });
    const columnMenu = page.locator(".project-column-menu");
    await expect(columnMenu).toBeVisible();
    await columnMenu.getByRole("checkbox", { name: "외부 ID", exact: true }).check();
    await columnMenu.getByRole("checkbox", { name: "기간", exact: true }).uncheck();
    await page.keyboard.press("Escape");
    await expect(gridHeader.getByText("외부 ID", { exact: true })).toBeVisible();
    await expect(gridHeader.getByText("기간", { exact: true })).toHaveCount(0);
    const taskHeaderCell = gridHeader.getByText("작업", { exact: true }).locator("..");
    const widthBeforeResize = (await taskHeaderCell.boundingBox())!.width;
    const gripBox = await taskHeaderCell.locator(".wx-grip").boundingBox();
    if (!gripBox) throw new Error("Expected the task column resize grip.");
    await page.mouse.move(gripBox.x + gripBox.width / 2, gripBox.y + gripBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(gripBox.x + gripBox.width / 2 + 48, gripBox.y + gripBox.height / 2, { steps: 6 });
    await page.mouse.up();
    const resizedTaskWidth = (await taskHeaderCell.boundingBox())!.width;
    expect(resizedTaskWidth).toBeGreaterThan(widthBeforeResize + 20);
    const chart = page.locator(".project-gantt-widget .wx-chart").first();
    expect(await chart.evaluate((element) => element.scrollWidth)).toBeGreaterThan(await chart.evaluate((element) => element.clientWidth));
    await chart.evaluate((element) => { element.scrollLeft = 240; });
    await expect.poll(() => chart.evaluate((element) => element.scrollLeft)).toBeGreaterThan(0);
    const chartScrollLeft = await chart.evaluate((element) => element.scrollLeft);
    const pageScrollTop = await page.evaluate(() => window.scrollY);
    const gridBoxBeforePending = await page.locator(".project-gantt-widget .wx-table-container").boundingBox();
    expect(gridBoxBeforePending).not.toBeNull();
    const gate = deferred(); const started = deferred();
    fixture.nextPost = { kind: "success", gate, started };
    await rootAdd(page).click(); await started.promise;
    await expect(page.locator(".project-schedule .schedule-saving[role=status]")).toContainText("일정 저장 중");
    await expect(page.locator('.project-schedule[aria-busy="true"]')).toBeVisible();
    await expect(ganttRoot(page)).toHaveAttribute("data-task-mutation-locked", "true");
    await expect(rootAdd(page)).toBeVisible();
    await expect(rootAdd(page)).toHaveAttribute("aria-disabled", "true");
    expect(await rootAdd(page).evaluate((element) => getComputedStyle(element).pointerEvents)).toBe("none");
    await expect(page.locator(".loading-state")).toHaveCount(0);
    await expect(page.locator(".project-gantt-widget .wx-chart")).toBeVisible();
    await expectSameGanttRoot(page, identity);
    const gridBoxWhilePending = await page.locator(".project-gantt-widget .wx-table-container").boundingBox();
    expect(gridBoxWhilePending).not.toBeNull();
    expect(gridBoxWhilePending!.width).toBeCloseTo(gridBoxBeforePending!.width, 0);
    // Pointer 스타일을 우회한 이벤트도 동기 mutation lock이 막아야 한다.
    await rootAdd(page).dispatchEvent("click"); await waitForAnimationFrame(page);
    expect(fixture.posts).toHaveLength(1);
    await expect(page.locator(".project-schedule .schedule-saving[role=status]")).toContainText("일정 저장 중");
    await expect(page.locator(".form-status")).toHaveCount(0);
    gate.resolve();
    await expect(page.getByTestId("workspace-toast")).toContainText("작업을 추가했습니다");
    await expect(ganttRoot(page)).not.toHaveAttribute("data-task-mutation-locked", "true");
    await expect(rootAdd(page)).toHaveAttribute("aria-disabled", "false");
    expect(fixture.createdTaskIds).toHaveLength(1);
    const firstCreatedTaskId = fixture.createdTaskIds[0];
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(1);
    await expect(page.locator(`.wx-bar[data-task-id=":${firstCreatedTaskId}"]`)).toHaveCount(1);
    await expectSameGanttRoot(page, identity);
    await expect(selectedRow).toHaveClass(/wx-selected/);
    await expect(summaryToggle).toHaveClass(/wxi-menu-right/);
    await expect(page.getByRole("grid").getByText("Existing summary child", { exact: true })).toHaveCount(0);
    await expect(gridHeader.getByText("외부 ID", { exact: true })).toBeVisible();
    await expect(gridHeader.getByText("기간", { exact: true })).toHaveCount(0);
    expect((await taskHeaderCell.boundingBox())!.width).toBeCloseTo(resizedTaskWidth, 0);
    expect(await chart.evaluate((element) => element.scrollLeft)).toBeCloseTo(chartScrollLeft, 0);
    expect(await page.evaluate(() => window.scrollY)).toBe(pageScrollTop);
    for (let index = 1; index < 10; index += 1) {
      const responsePromise = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === taskPath);
      await rootAdd(page).click(); expect((await responsePromise).status()).toBe(201);
      await expect.poll(() => fixture.createdTaskIds.length).toBe(index + 1);
      await expect(page.locator(`.wx-bar[data-task-id=":${fixture.createdTaskIds[index]}"]`)).toHaveCount(1);
      await expectSameGanttRoot(page, identity);
    }
    expect(fixture.posts).toHaveLength(10); expect(fixture.patchRequests).toHaveLength(0);
    expect(fixture.project.revision).toBe(fixture.initialRevision + 10);
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(10);
    await expect(selectedRow).toHaveClass(/wx-selected/);
    await expect(summaryToggle).toHaveClass(/wxi-menu-right/);
    await expect(gridHeader.getByText("외부 ID", { exact: true })).toBeVisible();
    await expect(gridHeader.getByText("기간", { exact: true })).toHaveCount(0);
    expect((await taskHeaderCell.boundingBox())!.width).toBeCloseTo(resizedTaskWidth, 0);
    expect(await chart.evaluate((element) => element.scrollLeft)).toBeCloseTo(chartScrollLeft, 0);
    await waitForAnimationFrame(page);
    expect(documentRequests).toEqual([]); expect(navigations).toEqual([]);
    page.off("request", recordDocument); page.off("framenavigated", recordNavigation);
    const persistedTaskIds = [...fixture.createdTaskIds];
    await page.reload();
    await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(10);
    for (const taskId of persistedTaskIds) await expect(page.locator(`.wx-bar[data-task-id=":${taskId}"]`)).toHaveCount(1);
  });

  test("확인 팝업 없이 첫 하위 작업을 추가하고 모든 보호 오류에서 유령 작업을 남기지 않는다", async ({ page }) => {
    await page.clock.setFixedTime(new Date("2026-09-16T12:00:00.000Z"));
    const fixture = await installStatefulProjectFixture(page);
    await page.goto(`/projects/${publicId}`);
    await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
    const initialIdentity = await rememberGanttRoot(page);
    const documentRequests: string[] = []; const navigations: string[] = [];
    page.on("request", (request) => { if (request.resourceType() === "document") documentRequests.push(request.url()); });
    page.on("framenavigated", (frame) => { if (frame === page.mainFrame()) navigations.push(frame.url()); });
    const leafRow = rowNamed(page, "Stable leaf");
    const firstChildResponse = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === taskPath);
    await leafRow.locator('[data-action="add-task"]').click();
    expect((await firstChildResponse).status()).toBe(201);
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(page.getByTestId("workspace-toast")).toContainText("작업을 추가했습니다");
    expect(fixture.posts).toHaveLength(1);
    expect(fixture.posts[0]).toMatchObject({ parentTaskId: "00000000-0000-4000-8000-000000000003", convertParentToSummary: true });
    expect(fixture.tasks.find((entry) => entry.externalId === "LEAF-1")?.type).toBe("summary");
    await expect(page.locator(`.wx-bar[data-task-id=":${fixture.createdTaskIds[0]}"]`)).toHaveCount(1);
    await expectSameGanttRoot(page, initialIdentity);
    const secondChildResponse = page.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === taskPath);
    await rowNamed(page, "Stable leaf").locator('[data-action="add-task"]').click();
    expect((await secondChildResponse).status()).toBe(201);
    await expect(page.getByRole("dialog")).toHaveCount(0);
    expect(fixture.posts).toHaveLength(2);
    expect(fixture.posts[1]).toMatchObject({ parentTaskId: "00000000-0000-4000-8000-000000000003" });
    expect(fixture.posts[1]).not.toHaveProperty("convertParentToSummary");
    await expectSameGanttRoot(page, initialIdentity);
    await page.getByRole("button", { name: "프로젝트 설정", exact: true }).click();
    await page.getByRole("button", { name: "편집 모드 종료" }).click();
    await expect(page.getByText("읽기 전용", { exact: true })).toBeVisible();
    await expect(rootAdd(page)).toHaveCount(0);
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(2);
    for (const taskId of fixture.createdTaskIds) await expect(page.locator(`.wx-bar[data-task-id=":${taskId}"]`)).toHaveCount(1);
    await expectSameGanttRoot(page, initialIdentity);
    await submitProjectUnlock(page, "issue-3-password");
    await expect(page.getByText("편집 중", { exact: true })).toBeVisible();
    await expect(rootAdd(page)).toBeVisible();
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(2);
    await expectSameGanttRoot(page, initialIdentity);
    await rowNamed(page, "Stable milestone").locator('[data-action="add-task"]').click();
    await expect(page.getByTestId("workspace-toast")).toContainText("마일스톤에는 하위 작업을 추가할 수 없습니다");
    expect(fixture.posts).toHaveLength(2);
    async function rejectNextAdd(outcome: PostOutcome, expectedNotice: string, trigger = rootAdd(page)): Promise<void> {
      const taskCount = fixture.tasks.length; const postCount = fixture.posts.length;
      fixture.nextPost = outcome; await trigger.click();
      await expect(page.getByTestId("workspace-toast")).toContainText(expectedNotice);
      expect(fixture.posts).toHaveLength(postCount + 1); expect(fixture.tasks).toHaveLength(taskCount);
      expect(fixture.createdTaskIds).toHaveLength(2);
      await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(2);
      expect(fixture.patchRequests).toHaveLength(0);
    }
    await rejectNextAdd({ kind: "error", status: 422, code: "INVALID_PARENT_TASK" }, "마일스톤에는 하위 작업을 추가할 수 없습니다", rowNamed(page, "Stable summary").locator('[data-action="add-task"]'));
    await rejectNextAdd({ kind: "error", status: 412, code: "REVISION_MISMATCH" }, "다른 편집 내용이 먼저 저장되었습니다");
    await rejectNextAdd({ kind: "error", status: 500, code: "INTERNAL_ERROR" }, "작업을 저장할 수 없습니다");
    await rejectNextAdd({ kind: "network" }, "네트워크 연결을 확인한 뒤 다시 시도해 주세요");
    await rejectNextAdd({ kind: "error", status: 401, code: "EDIT_SESSION_INVALID" }, "편집 권한이 만료되었습니다");
    await expect(page.getByText("읽기 전용", { exact: true })).toBeVisible();
    await expect(rootAdd(page)).toHaveCount(0);
    expect(documentRequests).toEqual([]); expect(navigations).toEqual([]);
  });
});
