import { expect, test, isolatedApplicationOptions } from "./fixtures/isolated-application";

const syntheticAdminPassword="Calendar261TestOnly!";
test.use({...isolatedApplicationOptions,isolatedResourceAdminPassword:syntheticAdminPassword,viewport:{width:1440,height:900}});

test("실제 SQLite에 그룹·리소스 WORKING 예외를 저장하고 재열기 후 일정·Gantt 상태를 보존한다",async({page,baseURL},testInfo)=>{
  const headers={Origin:baseURL!};
  expect((await page.request.post("/api/resource-catalog/admin-sessions",{headers,data:{password:syntheticAdminPassword}})).status()).toBe(201);
  let catalog=(await(await page.request.get("/api/resources")).json()).data;
  const resourceResponse=await page.request.post("/api/resources",{headers:{...headers,"If-Match":`"${catalog.revision}"`},data:{name:"홍길동"}});
  expect(resourceResponse.status()).toBe(201);
  catalog=(await resourceResponse.json()).data;
  const resourceId=catalog.resources[0].id;
  const groupResponse=await page.request.post("/api/resource-groups",{headers:{...headers,"If-Match":`"${catalog.revision}"`},data:{name:"설계팀"}});
  expect(groupResponse.status()).toBe(201);
  catalog=(await groupResponse.json()).data;
  const groupId=catalog.groups[0].id;
  expect((await page.request.put(`/api/resource-groups/${groupId}/members`,{headers:{...headers,"If-Match":`"${catalog.revision}"`},data:{resourceIds:[resourceId]}})).status()).toBe(200);
  const created=await page.request.post("/api/projects",{headers,data:{name:"Calendar persistence #261",ownerName:"E2E 자동화",description:"근무일 저장 검증",editPassword:"Calendar261!"}});
  expect(created.status()).toBe(201);
  const project=(await created.json()).data.project;
  const api=`/api/projects/${project.publicId}`;
  const taskResponse=await page.request.post(`${api}/tasks`,{headers:{...headers,"If-Match":`"${project.revision}"`},data:{name:"일정 보존 작업",type:"task",scheduleMode:"auto",start:"2026-11-02",duration:43,progress:0}});
  expect(taskResponse.status()).toBe(201);
  const before=(await(await page.request.get(api)).json()).data;
  await page.goto(`/projects/${project.publicId}`);
  const frame=page.locator("[data-project-gantt-instance]");
  await expect(frame).toHaveCount(1);
  const instance=await frame.getAttribute("data-project-gantt-instance");
  const apiInstance=await frame.getAttribute("data-project-gantt-api-instance");
  const row=page.locator('.wx-row[role="row"]').filter({hasText:"일정 보존 작업"});
  await row.locator('[role="gridcell"][data-col-id=":projectStart"]').click();
  await expect(row).toHaveClass(/wx-selected/);
  const chart=page.locator(".project-gantt-widget .wx-chart");
  await chart.evaluate((element)=>{element.scrollLeft=120;});
  const scroll=await chart.evaluate((element)=>element.scrollLeft);
  expect(scroll).toBeGreaterThan(0);
  await page.getByRole("button",{name:"프로젝트 설정",exact:true}).click();
  const dialog=page.getByRole("dialog",{name:"프로젝트 설정",exact:true});
  await dialog.getByRole("tab",{name:"작업 캘린더"}).click();
  for(const [index,type,target,name] of [[1,"RESOURCE_GROUP",groupId,"그룹 토요일 근무"],[2,"RESOURCE",resourceId,"개인 토요일 근무"]] as const) {
    await dialog.getByRole("button",{name:"날짜 예외 추가"}).click();
    await dialog.getByLabel(`날짜 예외 ${index} 이름`).fill(name);
    await dialog.getByLabel(`예외 날짜 ${index}`).fill("2026-10-03");
    await dialog.getByLabel(`예외 대상 ${index}`).selectOption(type);
    await dialog.getByLabel(`대상 선택 ${index}`).selectOption(target);
    await dialog.getByLabel(`일 유형 ${index}`).selectOption("WORKING");
  }
  await dialog.getByRole("button",{name:"미리보기 계산"}).click();
  await expect(dialog.locator("p[aria-atomic='true']")).toContainText("미리보기 계산 완료");
  await expect(dialog.getByText(/2026-10-03 · 리소스 그룹 설계팀/)).toContainText("적용됨");
  await expect(dialog.getByText(/2026-10-03 · 리소스 홍길동/)).toContainText("현재 효과 없음");
  await page.screenshot({path:testInfo.outputPath("calendar-exceptions-real-preview.png"),fullPage:true});
  const canonicalRead=page.waitForResponse((response)=>response.request().method()==="GET" && new URL(response.url()).pathname===`${api}/work-calendar`);
  const saved=page.waitForResponse((response)=>response.request().method()==="PUT" && new URL(response.url()).pathname===`${api}/work-calendar`);
  await dialog.getByRole("button",{name:"작업 캘린더 저장"}).click();
  expect((await saved).status()).toBe(200);
  expect((await canonicalRead).status()).toBe(200);
  await expect(page.getByTestId("workspace-toast")).toContainText("작업 캘린더를 저장했습니다");
  const calendar=(await(await page.request.get(`${api}/work-calendar`)).json()).data;
  expect(calendar.customDates).toHaveLength(2);
  expect(calendar.customDates.every((entry:{dayType:string})=>entry.dayType==="WORKING")).toBe(true);
  const after=(await(await page.request.get(api)).json()).data;
  expect(after.tasks).toEqual(before.tasks);
  expect(after.links).toEqual(before.links);
  await page.keyboard.press("Escape");
  await expect(frame).toHaveAttribute("data-project-gantt-instance",instance!);
  await expect(frame).toHaveAttribute("data-project-gantt-api-instance",apiInstance!);
  await expect(row).toHaveClass(/wx-selected/);
  expect(await chart.evaluate((element)=>element.scrollLeft)).toBeCloseTo(scroll,0);
  await page.getByRole("button",{name:"프로젝트 설정",exact:true}).click();
  await dialog.getByRole("tab",{name:"작업 캘린더"}).click();
  await expect(dialog.getByLabel("일 유형 1")).toHaveValue("WORKING");
  await expect(dialog.getByLabel("일 유형 2")).toHaveValue("WORKING");
});
