import { readFile } from "node:fs/promises";
import { expect, test, isolatedApplicationOptions } from "./fixtures/isolated-application";
import { capture491, createSource491, description491, fixturePassword491, importFile491, name491, openMore491, writeSafe491 } from "./helpers/issue491-transfer-fixture";
import type { Page } from "@playwright/test";

test.use({ ...isolatedApplicationOptions, locale:"ko-KR", timezoneId:"Asia/Seoul",actionTimeout:10_000 });
test.setTimeout(180_000);

test("Issue #491: readonly Excel·JSON·SVG·PNG 옵션·날짜 validation·pending·stale와 실제 다운로드",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);await page.request.delete(`${source.path}/edit-sessions/current`,{headers:{Origin:baseURL!}});await page.reload();await expect(page.getByText("읽기 전용",{exact:true})).toBeVisible();await page.getByRole("button",{name:"내보내기",exact:true}).click();const dialog=page.getByRole("dialog",{name:"내보내기",exact:true}),format=dialog.getByLabel("형식",{exact:true});await expect(format).toBeFocused();await capture491(page,info,"export-excel-options");await dialog.getByRole("checkbox",{name:"리소스 공수 견적 포함 (역할·개발자 Summary/Detail)",exact:true}).check();await dialog.getByRole("checkbox",{name:"물류 구성 보고서 포함 (공정·설비·시스템·연결 시트)",exact:true}).check();await capture491(page,info,"export-effort-options");
  await format.selectOption("svg");await dialog.getByRole("radio",{name:"날짜 범위 (차트만)",exact:true}).check();await capture491(page,info,"export-image-range");await dialog.getByRole("button",{name:"내보내기",exact:true}).click();await expect(dialog.getByLabel("시작일",{exact:true})).toHaveAttribute("aria-invalid","true");await capture491(page,info,"export-image-validation");await format.focus();await page.keyboard.press("Tab");await page.keyboard.press("Tab");await expect(dialog.getByLabel("시작일",{exact:true})).toBeFocused();await capture491(page,info,"export-date-native-focus","dialog[open]","native format → range radio → date Tab",[390,1440]);await dialog.getByLabel("시작일",{exact:true}).fill("2026-10-06");await dialog.getByLabel("종료일",{exact:true}).fill("2026-10-20");
  const gate=await gate491(page,`**${source.path}/exports/*`,"POST");gate.mode="500";gate.hold=true;await dialog.getByRole("button",{name:"내보내기",exact:true}).click();await expect(format).toBeDisabled();await page.keyboard.press("Escape");await page.keyboard.press("Escape");await expect(dialog).toBeVisible();await capture491(page,info,"export-pending","dialog[open]","controlled deferred SVG500");await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.hold=false;gate.release!();await expect(dialog.getByRole("alert")).toContainText("생성할 수 없습니다");await capture491(page,info,"export-error","dialog[open]","controlled export500");gate.mode="412";await dialog.getByRole("button",{name:"내보내기",exact:true}).click();await expect(dialog.getByRole("alert")).toContainText("변경되었습니다");await capture491(page,info,"export-stale","dialog[open]","controlled export412; options retained");gate.mode="continue";
  const downloads=[];for(const value of ["excel","json","svg","png"]){await format.selectOption(value);if(value==="svg"||value==="png")await dialog.getByRole("radio",{name:"프로젝트 전체 (Grid와 차트)",exact:true}).check();await capture491(page,info,`export-${value}-readonly`);const downloadPromise=page.waitForEvent("download"),responsePromise=page.waitForResponse(r=>r.request().method()==="POST"&&new URL(r.url()).pathname.startsWith(`${source.path}/exports/`));await dialog.getByRole("button",{name:"내보내기",exact:true}).click();const response=await responsePromise;expect(response.status()).toBe(200);const download=await downloadPromise;const bytes=await readFile((await download.path())!);if(value==="excel")expect(bytes.subarray(0,2).toString()).toBe("PK");if(value==="png")expect(bytes.subarray(0,8).toString("hex")).toBe("89504e470d0a1a0a");if(value==="svg"){expect(bytes.toString()).toContain("<svg");expect(bytes.toString()).not.toContain("<script");}if(value==="json"){const data=JSON.parse(bytes.toString());expect(data.schemaVersion).toBe("1.1");expect(bytes.toString()).not.toContain("editPassword");expect(bytes.toString()).not.toContain(fixturePassword491);}downloads.push({format:value,status:response.status(),bytes:bytes.length,filename:download.suggestedFilename()});await expect(dialog).toHaveCount(0);await page.getByRole("button",{name:"내보내기",exact:true}).click();await expect(format).toBeEnabled();}
  await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(page.getByRole("button",{name:"내보내기",exact:true})).toBeFocused();expect((await(await page.request.get(source.path)).json()).data).toEqual(source.snapshot);await writeSafe491(info,"export-contract",{downloads,requests:gate.requests,readonlySupported:true,sourceUnchanged:true,normalEscapeRestore:true,realExcelDrm:"NOT TESTED",fullWorkbookFormulaRegression:"NOT TESTED: existing dedicated tests own semantic coverage"});
});

test("Issue #491: 실제 inline 공수 옵션·빈 결과·큰 서버 표시값과 native 필터",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);await page.getByRole("tab",{name:"리소스",exact:true}).click();const panel=page.locator(".project-resource-workload");await expect(panel.getByRole("button",{name:"M/M",exact:true})).toBeDisabled();await expect(panel.getByRole("button",{name:"M/M",exact:true})).toHaveAttribute("title","M/M 환산 기준 미설정");await capture491(page,info,"effort-actual-empty",".project-resource-workload");await panel.getByRole("button",{name:"개발 견적",exact:true}).click();await expect(panel.getByRole("button",{name:"개발 견적",exact:true})).toHaveAttribute("aria-pressed","true");await panel.locator("button[aria-controls=resource-advanced-filter]").click();await panel.getByLabel("Task 기간 From",{exact:true}).fill("2026-10-06");await capture491(page,info,"effort-date-partial",".project-resource-workload");
  const actual=await(await page.request.get(`${source.path}/resource-workload`)).json();const large={...actual,data:{...actual.data,mdPerMm:20,grandTotalMd:999999.99,grandTotalMm:49999.9995}};await page.route(`**${source.path}/resource-workload*`,route=>route.fulfill({json:large}));await panel.getByRole("button",{name:"새로고침",exact:true}).click();await expect(panel.getByRole("button",{name:"M/M",exact:true})).toBeEnabled();await capture491(page,info,"effort-large-server-values",".project-resource-workload","formal response fixture; actual API baseline cloned, no effort algorithm assertion");await panel.getByRole("button",{name:"M/M",exact:true}).click();await expect(panel.getByRole("button",{name:"M/M",exact:true})).toHaveAttribute("aria-pressed","true");await panel.getByLabel("Task 기간 To",{exact:true}).fill("2026-10-01");await capture491(page,info,"effort-date-reversed",".project-resource-workload","formal workload fixture; local option display");await panel.getByLabel(/^종류/).focus();await page.keyboard.press("Tab");await expect(panel.getByLabel(/^상태/)).toBeFocused();await capture491(page,info,"effort-filter-native-focus",".project-resource-workload","native Tab within filter",[390,1440]);await page.keyboard.press("Escape");await expect(panel.locator("button[aria-controls=resource-advanced-filter]")).toBeFocused();await writeSafe491(info,"effort-contract",{actualApiStatus:200,actualAssignmentCount:actual.data.groups.reduce((n:number,g:{resources:unknown[]})=>n+g.resources.length,0),actualMmUnconfigured:true,serverFixtureMm:20,largeDisplayOnly:true,separateEffortModal:"N/A: inline controls and Excel include checkbox are supported entries"});
});

test("Issue #491: 전송 dialog와 템플릿 저장의 Gantt 범위·열·tree·선택·scroll 및 fullscreen 보존",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!,true);const nestedId=source.nestedId;await page.reload();await page.setViewportSize({width:1440,height:900});const frame=page.locator(".project-gantt-frame"),row=(id:string)=>frame.locator(`.wx-table-container .wx-row[data-id=":${id}"]`);await row(source.summaryId).click({button:"right",position:{x:12,y:19}});await page.getByRole("menuitem",{name:"최상위로 열기 (작업공간 탭)",exact:true}).click();await expect(page.getByRole("tablist",{name:"WBS 범위 탭"}).getByRole("tab",{name:"보존할 Summary",exact:true})).toHaveAttribute("aria-selected","true");const header=frame.locator(".wx-table-container .wx-header").first();await header.click({button:"right"});await page.locator(".project-column-menu").getByRole("checkbox",{name:"외부 ID",exact:true}).check();await page.keyboard.press("Escape");const taskHeader=header.getByText("작업",{exact:true}).locator("..");const prior=(await taskHeader.boundingBox())!.width,grip=(await taskHeader.locator(".wx-grip").boundingBox())!;await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();await page.mouse.move(grip.x+grip.width/2+48,grip.y+grip.height/2,{steps:6});await page.mouse.up();expect((await taskHeader.boundingBox())!.width).toBeGreaterThan(prior+20);await frame.getByRole("button",{name:"주",exact:true}).click();await row(nestedId).locator('[data-action="open-task"]').click();await row(source.snapshot.tasks.find((t:{externalId:string})=>t.externalId==="TRANSFER-1").taskId).click({button:"right",position:{x:12,y:19}});await page.keyboard.press("Escape");await frame.locator(".wx-chart").first().evaluate(n=>{n.scrollLeft=120;});await frame.locator(".wx-gantt").first().evaluate(n=>{n.scrollTop=38;});
  const state=async()=>({...await frame.evaluate(n=>({api:n.getAttribute("data-project-gantt-api-instance"),instance:n.getAttribute("data-project-gantt-instance"),viewport:Reflect.get(n,"__masterganttPublicViewport"),scale:n.getAttribute("data-gantt-scale-mode"),left:n.querySelector(".wx-chart")!.scrollLeft,top:n.querySelector(".wx-gantt")!.scrollTop,selected:Array.from(n.querySelectorAll('.wx-row[data-copy-selected="true"]')).map(r=>r.getAttribute("data-id")),tree:Array.from(n.querySelectorAll('[data-action="open-task"]')).map(r=>({id:r.closest("[data-id]")?.getAttribute("data-id"),closed:r.classList.contains("wxi-menu-right")})),scope:document.querySelector('.project-scope-tabs [aria-selected="true"]')?.textContent,rootTask:new URL(location.href).searchParams.get("rootTask")})),columns:await header.locator('[role="columnheader"]').evaluateAll(ns=>ns.map(n=>({id:n.getAttribute("data-header-id"),width:n.getBoundingClientRect().width})))});await expect.poll(async()=>(await state()).left).toBe(120);await expect.poll(async()=>(await state()).top).toBe(38);const before=await state();expect(before.selected).toHaveLength(1);expect(before.tree.some(t=>t.closed)).toBe(true);expect(before.columns.some(c=>c.id===":externalId")).toBe(true);const phases=[{phase:"prepared",state:before}];const persist=async()=>writeSafe491(info,"gantt-state-contract",{phases,nativeResizePixels:48,responseKind:"actual SQLite and installed Core",fullscreenModalEntry:"N/A: Project header outside native fullscreen host"});await persist();
  for(const [entry,title]of [["프로젝트 복사","프로젝트 복사"],["템플릿으로 저장","프로젝트 템플릿으로 저장"]]){await openMore491(page,entry);const dialog=page.getByRole("dialog",{name:title,exact:true});await expect(dialog.getByRole("button",{name:title==="프로젝트 복사"?"복사본 생성":"템플릿 저장",exact:true})).toBeEnabled();await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);phases.push({phase:`${entry} canceled`,state:await state()});await persist();await expect.poll(state).toEqual(before);}
  await page.getByRole("button",{name:"내보내기",exact:true}).click();await page.keyboard.press("Escape");await expect(page.getByRole("dialog",{name:"내보내기",exact:true})).toHaveCount(0);phases.push({phase:"export canceled",state:await state()});await persist();await expect.poll(state).toEqual(before);
  await openMore491(page,"템플릿으로 저장");const templateDialog=page.getByRole("dialog",{name:"프로젝트 템플릿으로 저장",exact:true});await expect(templateDialog.getByRole("button",{name:"템플릿 저장",exact:true})).toBeEnabled();await templateDialog.getByLabel("템플릿 이름",{exact:true}).fill("상태 보존 템플릿");await templateDialog.getByRole("button",{name:"템플릿 저장",exact:true}).click();await expect(templateDialog).toHaveCount(0);phases.push({phase:"actual template save success",state:await state()});await persist();await expect.poll(state).toEqual(before);
  await frame.getByRole("button",{name:"Gantt 전체 화면",exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement===document.querySelector(".project-gantt-frame"))).toBe(true);expect(await page.getByRole("button",{name:"내보내기",exact:true}).evaluate(n=>document.fullscreenElement!.contains(n))).toBe(false);await writeSafe491(info,"fullscreen-entry-scope",await page.getByRole("button",{name:"내보내기",exact:true}).evaluate(n=>{const r=n.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {headerInsideFullscreenHost:document.fullscreenElement!.contains(n),headerReceivesHit:hit===n||n.contains(hit),modalEntry:"N/A: header is outside fullscreen host",browserFullscreenEscape:"NOT TESTED: headless keyboard event did not invoke browser exit; original run4 FAIL preserved"};}));await frame.getByRole("button",{name:"Gantt 전체 화면 종료",exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement===null)).toBe(true);phases.push({phase:"native fullscreen round trip",state:await state()});await persist();await expect.poll(state).toEqual(before);await page.screenshot({path:info.outputPath("gantt-state.png")});
});

async function gate491(page: Page, pattern: string, method: string) {
  const gate = { mode:"continue" as "continue"|"500"|"401"|"412", hold:false, release:undefined as (()=>void)|undefined, requests:[] as Array<{method:string;path:string;Origin?:string;ifMatch?:string;status?:number}> };
  await page.route(pattern,async route=>{
    const request=route.request(); if(request.method()!==method){await route.continue();return;}
    const headers=await request.allHeaders();const record={method,path:new URL(request.url()).pathname,Origin:headers.origin,ifMatch:headers["if-match"],status:undefined as number|undefined};gate.requests.push(record);
    if(gate.hold)await new Promise<void>(resolve=>{gate.release=resolve;});
    if(gate.mode==="continue"){await route.continue();return;}
    record.status=Number(gate.mode);await route.fulfill({status:Number(gate.mode),json:{error:{code:gate.mode==="412"?"REVISION_MISMATCH":gate.mode==="401"?"EDIT_SESSION_REQUIRED":"CONTROLLED_UI_ERROR",message:"통제된 검증 오류"}}});
  });return gate;
}
async function seedTemplate491(page:Page,origin:string,source:{id:string;revision:number},name=name491) {
  const response=await page.request.post("/api/project-templates",{headers:{Origin:origin,"If-Match":`"${source.revision}"`},data:{sourceProjectPublicId:source.id,name,description:description491}});
  expect(response.status()).toBe(201);return (await response.json()).data;
}

// New-project navigation has a new publicId and intentionally creates a new workspace.
test("Issue #491: 빈 프로젝트 생성의 긴 필드·validation·pending·native 초안과 실제 성공",async({page},info)=>{
  await page.goto("/projects/new");const blank=page.getByRole("tab",{name:"빈 프로젝트 만들기",exact:true});
  await page.getByLabel("프로젝트 이름",{exact:true}).fill(name491);await page.getByLabel("소유자",{exact:true}).fill("긴 한국어 소유자 InternationalOwner");await page.locator("#project-description").fill(description491);
  await capture491(page,info,"create-long","main");
  await blank.focus();await page.keyboard.press("ArrowRight");await expect(page.getByRole("tab",{name:"템플릿에서 만들기",exact:true})).toBeFocused();await page.keyboard.press("Home");await expect(blank).toBeFocused();await page.keyboard.press("Tab");await expect(page.locator("#project-name")).toBeFocused();await capture491(page,info,"create-native-focus","main","native Tab after switching modes",[390,1440]);await expect(page.getByLabel("프로젝트 이름",{exact:true})).toHaveValue(name491);
  await page.getByRole("button",{name:"프로젝트 만들기",exact:true}).click();await expect(page.locator("#project-edit-password")).toHaveAttribute("aria-invalid","true");await capture491(page,info,"create-validation","main");
  const gate=await gate491(page,"**/api/projects","POST");gate.hold=true;await page.locator("#project-edit-password").fill(fixturePassword491);await page.getByRole("button",{name:"프로젝트 만들기",exact:true}).click();await expect(page.locator("#project-edit-password")).toBeDisabled();await expect(page.locator("#project-edit-password")).toHaveValue("");await capture491(page,info,"create-pending","main","actual POST held before network forwarding");
  await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.release!();await page.waitForURL(/\/projects\/[0-9a-f-]{36}$/);await expect(page.getByText("편집 중",{exact:true})).toBeVisible();expect(gate.requests).toHaveLength(1);const snapshot=(await (await page.request.get(`/api/projects/${page.url().split('/').at(-1)}`)).json()).data;
  expect(snapshot.project.name).toBe(name491);expect(snapshot.project.description).toBe(description491);await writeSafe491(info,"create-contract",{requests:gate.requests,status:201,newProjectReady:true,metadataPreserved:true,passwordCleared:true,workspaceNavigation:"new publicId; same-instance preservation N/A"});
});

test("Issue #491: 템플릿 저장의 긴 초안·validation·pending·401412·readonly와 실제 성공",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);await openMore491(page,"템플릿으로 저장");const dialog=page.getByRole("dialog",{name:"프로젝트 템플릿으로 저장",exact:true});const name=dialog.getByLabel("템플릿 이름",{exact:true}),description=dialog.getByLabel("설명 (선택)",{exact:true}),save=dialog.getByRole("button",{name:"템플릿 저장",exact:true});await expect(save).toBeEnabled();
  await name.fill(name491);await description.fill(description491);await capture491(page,info,"template-save-long");await name.focus();await page.keyboard.press("Tab");await expect(description).toBeFocused();await capture491(page,info,"template-save-native-focus","dialog[open]","native Tab from name to description",[390,1440]);await name.fill("");await save.click();await expect(dialog.getByRole("alert")).toContainText("1~200자");await capture491(page,info,"template-save-validation");await name.fill(name491);
  const gate=await gate491(page,"**/api/project-templates","POST");gate.mode="500";gate.hold=true;await save.click();await expect(name).toBeDisabled();await page.keyboard.press("Escape");await page.keyboard.press("Escape");await expect(dialog).toBeVisible();await capture491(page,info,"template-save-pending","dialog[open]","controlled deferred template500");await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.hold=false;gate.release!();await expect(dialog.getByRole("alert")).toContainText("통제된 검증 오류");await expect(name).toHaveValue(name491);await capture491(page,info,"template-save-error","dialog[open]","controlled template500");
  gate.mode="412";await save.click();await expect(dialog.getByRole("alert")).toContainText("변경되었습니다");await capture491(page,info,"template-save-stale","dialog[open]","controlled template412");await dialog.getByRole("button",{name:"최신 원본 확인",exact:true}).click();await expect(save).toBeEnabled();await expect(description).toHaveValue(description491);
  gate.mode="401";await save.click();await expect(dialog.getByLabel("프로젝트 편집 비밀번호",{exact:true})).toBeFocused();await expect(dialog.getByLabel("프로젝트 편집 비밀번호",{exact:true})).toHaveValue("");await capture491(page,info,"template-save-401","dialog[open]","controlled template401");await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(page.getByRole("button",{name:"템플릿으로 저장",exact:true})).toBeFocused();
  await page.request.delete(`${source.path}/edit-sessions/current`,{headers:{Origin:baseURL!}});await page.reload();await openMore491(page,"템플릿으로 저장");await expect(save).toBeEnabled();await expect(dialog.getByLabel("프로젝트 편집 비밀번호",{exact:true})).toBeVisible();await capture491(page,info,"template-save-readonly");gate.mode="continue";await dialog.getByLabel("프로젝트 편집 비밀번호",{exact:true}).fill(fixturePassword491);const responsePromise=page.waitForResponse(r=>r.request().method()==="POST"&&new URL(r.url()).pathname==="/api/project-templates");await save.click();expect((await responsePromise).status()).toBe(201);await expect(dialog).toHaveCount(0);expect((await(await page.request.get(source.path)).json()).data).toEqual(source.snapshot);await writeSafe491(info,"template-save-contract",{actualStatus:201,sourceUnchanged:true,requests:gate.requests,staleDraftPreserved:true,normalEscapeRestore:true,successFocus:await page.evaluate(()=>document.activeElement?.tagName)});
});

test("Issue #491: JSON Import preview·표 스크롤·validation·취소·commit pending·401412와 실제 추가",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);const file={setInputFiles:async(payload:ReturnType<typeof importFile491>)=>{const more=page.locator('summary[aria-label="프로젝트 작업 더보기"]');if(!await more.evaluate(n=>n.parentElement!.hasAttribute("open")))await more.click();const chooserPromise=page.waitForEvent("filechooser");await page.getByRole("button",{name:"가져오기 (JSON)",exact:true}).click();await(await chooserPromise).setFiles(payload);}};const dialog=page.getByRole("dialog",{name:"JSON 파일 가져오기",exact:true});const previewGate=await gate491(page,`**${source.path}/imports/preview`,"POST");previewGate.hold=true;await file.setInputFiles(importFile491("보존"));await expect(dialog.getByText("파일을 검증하는 중… 취소하면 이 조회를 중단합니다.",{exact:true})).toBeVisible();await capture491(page,info,"import-preview-pending","dialog[open]","actual preview request held; cancel is allowed");await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect.poll(()=>Boolean(previewGate.release)).toBe(true);previewGate.hold=false;previewGate.release!();
  await file.setInputFiles({name:"잘못된.json",mimeType:"application/json",buffer:Buffer.from("{")});await expect(dialog.getByRole("alert")).toBeVisible();await capture491(page,info,"import-validation","dialog[open]","actual malformed JSON400");await page.keyboard.press("Escape");
  await file.setInputFiles(importFile491("보존"));const commit=dialog.getByRole("button",{name:"기존 일정에 추가",exact:true});await expect(commit).toBeEnabled();await capture491(page,info,"import-preview-long");await page.setViewportSize({width:390,height:900});const tableOwner=dialog.getByRole("region",{name:"가져오기 작업 미리보기 가로 스크롤",exact:true});await tableOwner.scrollIntoViewIfNeeded();await dialog.getByRole("button",{name:"취소",exact:true}).focus();await page.keyboard.press("Tab");await page.keyboard.press("Tab");await page.keyboard.press("Tab");await page.keyboard.press("Tab");
  // Traverse native Tab order rather than synthesize a focused screenshot.
  for(let i=0;i<20&&!await tableOwner.evaluate(n=>n===document.activeElement);i++)await page.keyboard.press("Tab");await expect(tableOwner).toBeFocused();const tableGeometry=await tableOwner.evaluate(n=>({viewportWidth:innerWidth,clientWidth:n.clientWidth,scrollWidth:n.scrollWidth,tableWidth:n.querySelector("table")!.getBoundingClientRect().width}));await capture491(page,info,"import-table-native-focus","dialog[open]","actual populated preview; native Tab focus owner",[390,1440]);expect(tableGeometry.scrollWidth).toBeGreaterThan(tableGeometry.clientWidth);await writeSafe491(info,"import-table-owner",tableGeometry);
  const gate=await gate491(page,`**${source.path}/imports`,"POST");gate.hold=true;gate.mode="412";await commit.click();await expect(dialog.getByRole("button",{name:"추가 중…",exact:true})).toBeDisabled();await page.keyboard.press("Escape");await page.keyboard.press("Escape");await expect(dialog).toBeVisible();await capture491(page,info,"import-commit-pending","dialog[open]","controlled deferred commit412");await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.hold=false;gate.release!();await expect(dialog.getByRole("alert")).toContainText("변경되었습니다");await capture491(page,info,"import-stale","dialog[open]","controlled commit412");await dialog.getByRole("button",{name:"최신 일정 조회",exact:true}).click();await expect(dialog.getByRole("button",{name:"다시 미리보기",exact:true})).toBeEnabled();await dialog.getByRole("button",{name:"다시 미리보기",exact:true}).click();await expect(commit).toBeEnabled();gate.mode="401";await commit.click();await expect(dialog.getByRole("alert")).toContainText("만료되었습니다");await capture491(page,info,"import-401","dialog[open]","controlled commit401; file retained, local readonly");await page.keyboard.press("Escape");
  const unlock=await page.request.post(`${source.path}/edit-sessions`,{headers:{Origin:baseURL!},data:{editPassword:fixturePassword491}});expect(unlock.status()).toBe(204);await page.reload();gate.mode="continue";await file.setInputFiles(importFile491("실제"));await expect(commit).toBeEnabled();const ganttIdentity=await page.locator(".project-gantt-frame").evaluate(n=>({api:n.getAttribute("data-project-gantt-api-instance"),instance:n.getAttribute("data-project-gantt-instance"),scale:n.getAttribute("data-gantt-scale-mode")}));const responsePromise=page.waitForResponse(r=>r.request().method()==="POST"&&new URL(r.url()).pathname===`${source.path}/imports`);await commit.click();expect((await responsePromise).status()).toBe(201);await expect(dialog).toHaveCount(0);expect(await page.locator(".project-gantt-frame").evaluate(n=>({api:n.getAttribute("data-project-gantt-api-instance"),instance:n.getAttribute("data-project-gantt-instance"),scale:n.getAttribute("data-gantt-scale-mode")}))).toEqual(ganttIdentity);const after=(await(await page.request.get(source.path)).json()).data;expect(after.tasks).toHaveLength(source.snapshot.tasks.length+1);for(const task of source.snapshot.tasks)expect(after.tasks.find((t:{taskId:string})=>t.taskId===task.taskId)).toEqual(task);expect(after.links).toEqual(source.snapshot.links);const csv=await page.request.post(`${source.path}/imports/preview`,{headers:{Origin:baseURL!,"Content-Type":"text/csv"},data:"name,duration\nsynthetic,1"});expect(csv.status()).toBe(415);await writeSafe491(info,"import-contract",{actualPreviewReady:true,actualCommitStatus:201,ganttInstanceApiScalePreserved:true,addedTaskCount:1,existingTasksLinksUnchanged:true,requests:gate.requests,previewCancelAllowed:true,commitRepeatedEscapeBlocked:true,csvStatus:415,csvMappingUi:"N/A: accept JSON only; no mapping entry"});
});

test("Issue #491: 템플릿 목록·선택·큰 표시값·validation·pending과 실제 생성",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);const template=await seedTemplate491(page,baseURL!,source);expect(template.id).toBeTruthy();
  let listMode:"hold"|"error"|"empty"|"actual"|"large"="hold";let release:(()=>void)|undefined;
  await page.route("**/api/project-templates?activeOnly=true",async route=>{
    if(listMode==="hold")await new Promise<void>(resolve=>{release=resolve;});
    if(listMode==="error"){await route.fulfill({status:500,json:{}});return;}
    if(listMode==="empty"){await route.fulfill({json:{data:[]}});return;}
    if(listMode==="large"){await route.fulfill({json:{data:[{...template,taskCount:5000,milestoneCount:5000,processCount:9999,equipmentCount:9999,systemCount:9999}]}});return;}
    await route.continue();
  });
  await page.goto("/projects/new?mode=template");await expect(page.getByText("템플릿 정보를 불러오는 중입니다…",{exact:true})).toBeVisible();await capture491(page,info,"template-list-loading","main","held template GET");listMode="error";await expect.poll(()=>Boolean(release)).toBe(true);release!();await expect(page.locator("#panel-template [role=alert]")).toContainText("불러오지 못했습니다");await capture491(page,info,"template-list-error","main","controlled GET500");
  listMode="empty";await page.getByRole("button",{name:"템플릿 목록 다시 시도"}).click();await expect(page.getByText("등록된 프로젝트 템플릿이 없습니다.",{exact:true})).toBeVisible();await capture491(page,info,"template-list-empty","main","controlled empty catalog");
  listMode="large";await page.reload();await expect(page.getByRole("radio",{name:name491,exact:true})).toBeChecked();await page.locator("#inst-project-name").fill("사용자 이름 초안");await capture491(page,info,"template-large-counts","main","formal catalog fixture with large display counts; not actual task creation");
  listMode="actual";await page.reload();await expect(page.getByRole("radio",{name:name491,exact:true})).toBeChecked();await page.locator("#inst-project-name").fill(name491);await page.locator("#inst-desc").fill(description491);await capture491(page,info,"template-create-long","main");
  await page.getByRole("radio",{name:name491,exact:true}).focus();await page.keyboard.press("Space");await page.keyboard.press("Tab");await expect(page.locator("#inst-project-name")).toBeFocused();await capture491(page,info,"template-create-native-focus","main","native Radio Space and Tab",[390,1440]);
  await page.getByRole("button",{name:"템플릿에서 프로젝트 생성",exact:true}).click();await expect(page.locator("#inst-owner-name")).toHaveAttribute("aria-invalid","true");await capture491(page,info,"template-create-validation","main");
  await page.locator("#inst-owner-name").fill("E2E 자동화");await page.locator("#inst-start-date").fill("2026-10-06");await page.locator("#inst-password").fill(fixturePassword491);const gate=await gate491(page,`**/api/project-templates/${template.id}/instantiate`,"POST");gate.hold=true;
  await page.getByRole("button",{name:"템플릿에서 프로젝트 생성",exact:true}).click();await expect(page.locator("#inst-password")).toBeDisabled();await expect(page.locator("#inst-password")).toHaveValue("");await capture491(page,info,"template-create-pending","main","actual instantiate held before forwarding");await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.release!();await page.waitForURL(/\/projects\/[0-9a-f-]{36}$/);await expect(page.getByText("편집 중",{exact:true})).toBeVisible();expect(gate.requests).toHaveLength(1);
  expect((await (await page.request.get(source.path)).json()).data).toEqual(source.snapshot);await writeSafe491(info,"template-create-contract",{actualTemplateSaved:true,actualInstantiationStatus:201,requests:gate.requests,newProjectNavigation:true,sourceUnchanged:JSON.stringify((await (await page.request.get(source.path)).json()).data)===JSON.stringify(source.snapshot),csvMappingUi:"N/A: JSON-only import is a separate surface"});
});

test("Issue #491: 프로젝트 복사 loading·초안·pending·오류·401412·readonly와 실제 원본 보존",async({page,baseURL},info)=>{
  const source=await createSource491(page,baseURL!);const reads=await gate491(page,`**${source.path}`,"GET");reads.hold=true;await openMore491(page,"프로젝트 복사");const dialog=page.getByRole("dialog",{name:"프로젝트 복사",exact:true});await expect(dialog.getByText("원본 프로젝트를 확인하는 중…",{exact:true})).toBeVisible();await capture491(page,info,"copy-loading","dialog[open]","held source GET");await expect.poll(()=>Boolean(reads.release)).toBe(true);reads.hold=false;reads.release!();await expect(dialog.getByLabel("새 프로젝트명",{exact:true})).toBeEnabled();
  await dialog.getByLabel("새 프로젝트명",{exact:true}).fill(name491);await dialog.getByLabel("설명",{exact:true}).fill(description491);await capture491(page,info,"copy-long");await dialog.getByRole("button",{name:"복사본 생성",exact:true}).click();await expect(dialog.getByRole("alert")).toContainText("비밀번호");await capture491(page,info,"copy-validation");
  const gate=await gate491(page,`**${source.path}/copy`,"POST");
  const submit=async()=>{const sourceInput=dialog.getByLabel("원본 편집 비밀번호",{exact:true});if(await sourceInput.count())await sourceInput.fill(fixturePassword491);await dialog.getByLabel("새 편집 비밀번호",{exact:true}).fill(fixturePassword491);await dialog.getByLabel("새 편집 비밀번호 확인",{exact:true}).fill(fixturePassword491);await dialog.getByRole("button",{name:"복사본 생성",exact:true}).click();};
  gate.mode="500";gate.hold=true;await submit();await expect(dialog.getByLabel("새 프로젝트명",{exact:true})).toBeDisabled();await page.keyboard.press("Escape");await page.keyboard.press("Escape");await expect(dialog).toBeVisible();await capture491(page,info,"copy-pending","dialog[open]","controlled deferred copy500");await expect.poll(()=>Boolean(gate.release)).toBe(true);gate.hold=false;gate.release!();
  await expect(dialog.getByRole("alert")).toContainText("복사하지 못했습니다");await expect(dialog.getByLabel("새 프로젝트명",{exact:true})).toHaveValue(name491);await expect(dialog.getByLabel("새 편집 비밀번호",{exact:true})).toHaveValue("");await capture491(page,info,"copy-error","dialog[open]","controlled copy500");
  gate.mode="412";await submit();await expect(dialog.getByRole("alert")).toContainText("변경되었습니다");await capture491(page,info,"copy-stale","dialog[open]","controlled copy412");await dialog.getByRole("button",{name:"최신 원본 확인",exact:true}).click();await expect(dialog.getByRole("button",{name:"복사본 생성",exact:true})).toBeEnabled();await expect(dialog.getByLabel("설명",{exact:true})).toHaveValue(description491);
  gate.mode="401";await submit();await expect(dialog.getByLabel("원본 편집 비밀번호",{exact:true})).toBeFocused();await capture491(page,info,"copy-401","dialog[open]","controlled copy401; local source auth reset");
  await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(page.getByRole("button",{name:"프로젝트 복사",exact:true})).toBeFocused();
  await page.request.delete(`${source.path}/edit-sessions/current`,{headers:{Origin:baseURL!}});await page.reload();await expect(page.getByText("읽기 전용",{exact:true})).toBeVisible();await openMore491(page,"프로젝트 복사");await expect(dialog.getByLabel("원본 편집 비밀번호",{exact:true})).toBeVisible();await capture491(page,info,"copy-readonly");gate.mode="continue";
  await submit();await page.waitForURL(url=>url.pathname.startsWith("/projects/")&&!url.pathname.endsWith(source.id));expect((await (await page.request.get(source.path)).json()).data).toEqual(source.snapshot);await writeSafe491(info,"copy-contract",{sourceUnchanged:true,actualSuccessStatus:201,requests:gate.requests,newPublicIdNavigation:true,passwordClearedOnFailures:true,staleDraftPreserved:true});
});
