import { expect, test, isolatedApplicationOptions, submitProjectAndExpectCreated } from "./fixtures/isolated-application";
import type { ProjectSnapshotResponse } from "../../src/contracts/projects";

test.use(isolatedApplicationOptions);

test("creates name-only containers and preserves the same Core instance across first/last child and reload", async ({ page }) => {
  test.setTimeout(120_000);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/projects/new");
  await page.getByLabel("프로젝트 이름", { exact: true }).fill(`Empty Summary ${Date.now()}`);
  await page.getByLabel("편집 비밀번호", { exact: true }).fill("SumPwd123!");
  await submitProjectAndExpectCreated(page);
  await page.waitForURL(/\/projects\/[0-9a-f-]{36}$/);
  const api = `/api${new URL(page.url()).pathname}`;
  const mutations: unknown[] = [];
  page.on("request", (request) => { if (request.method() === "POST" && new URL(request.url()).pathname === `${api}/tasks`) mutations.push(request.postDataJSON()); });
  const frame = page.locator(".project-gantt-frame");
  const addSummary = page.getByRole("button", { name: "요약 작업 추가", exact: true });
  await addSummary.focus();
  await addSummary.press("Enter");
  let summaryName = page.getByRole("grid").getByText("새 요약 작업", { exact: true });
  await expect(summaryName).toBeVisible();
  const instance = await frame.getAttribute("data-project-gantt-api-instance");
  const stored = async () => await (await page.request.get(api)).json() as ProjectSnapshotResponse;
  let snapshot = await stored();
  const summary = snapshot.data.tasks[0];
  expect(summary).toMatchObject({ type: "summary", requestedStart: null, start: null, end: null, duration: null, progress: null });
  expect(mutations[0]).toEqual({ name: "새 요약 작업", type: "summary" });
  const row = page.locator(`.wx-table-container .wx-row[data-id=":${summary.taskId}"]`);
  await expect(row.locator('[data-col-id=":projectStart"]')).toHaveText("—");
  await expect(page.locator(`.wx-bar[data-task-id=":${summary.taskId}"]`)).toHaveCount(0);
  await expect(page.getByText("일정이 있는 하위 작업이 없습니다.", { exact: true })).toBeVisible();
  const rootName = "일정 미산정 요약 작업의 긴 한국어 이름과 구조를 유지합니다";
  await expect(frame).toHaveAttribute("data-task-inline-editable", "true");
  await row.locator('.wx-content > .wx-text').click();
  const nameInput = row.locator(".wx-cell.wx-editor input.wx-text");
  await expect(nameInput).toBeFocused();
  await nameInput.fill(rootName);
  await nameInput.press("Enter");
  summaryName = page.getByRole("grid").getByText(rootName, { exact: true });
  await expect(summaryName).toBeVisible();
  for (const width of [390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 844 });
    await expect(summaryName).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: `output/playwright/issue345-empty-${width}.png` });
  }
  await page.getByRole("button", { name: "주", exact: true }).click();
  for (let cycle = 0; cycle < 2; cycle++) {
    await row.locator('[data-action="add-task"]').click();
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toBeVisible();
    await expect(page.locator(`.wx-bar[data-task-id=":${summary.taskId}"]`)).toHaveCount(1);
    snapshot = await stored();
    expect(snapshot.data.tasks.find((task) => task.taskId === summary.taskId)?.start).not.toBeNull();
    await page.getByRole("grid").getByText("새 작업", { exact: true }).click({ button: "right" });
    await page.getByRole("menu", { name: "작업 메뉴", exact: true }).getByRole("menuitem", { name: "Delete", exact: true }).click();
    await expect(page.getByRole("grid").getByText("새 작업", { exact: true })).toHaveCount(0);
    await expect(summaryName).toBeVisible();
    await expect(page.locator(`.wx-bar[data-task-id=":${summary.taskId}"]`)).toHaveCount(0);
    await expect(frame).toHaveAttribute("data-project-gantt-api-instance", instance!);
    await expect(frame).toHaveAttribute("data-gantt-scale-mode", "week");
    const empty = (await stored()).data.tasks[0];
    expect(empty).toMatchObject({ taskId: summary.taskId, type: "summary", start: null, end: null, duration: null, progress: null });
  }
  await summaryName.click({ button: "right" });
  const menu = page.getByRole("menu", { name: "작업 메뉴", exact: true });
  await expect(menu.getByRole("menuitem", { name: "Edit", exact: true })).toBeVisible();
  await menu.getByRole("menuitem", { name: "Edit", exact: true }).click();
  const editor = page.getByRole("dialog", { name: "작업 정보", exact: true });
  await expect(editor).toBeVisible();
  await expect(editor.getByLabel("기간 미산정", { exact: true })).toHaveText("—");
  await expect(editor.getByLabel("진행률 미산정", { exact: true })).toHaveText("—");
  await expect(editor.getByText("변경한 일정을 먼저 저장", { exact: false })).toHaveCount(0);
  await editor.press("Escape");
  await expect(editor).toHaveCount(0);
  await expect(menu).toHaveCount(0);
  await page.reload();
  await expect(summaryName).toBeVisible();
  await expect(page.locator(`.wx-bar[data-task-id=":${summary.taskId}"]`)).toHaveCount(0);
  const reload = await stored();
  expect(reload.data.tasks).toHaveLength(1);
  expect(reload.data.tasks[0].start).toBeNull();
  // Build nested containers through the existing Add submenu, then move its
  // sole dated child out through the supported hierarchy command.
  await summaryName.click({ button: "right" });
  await page.getByRole("menu", { name: "작업 메뉴", exact: true }).getByRole("menuitem", { name: "Add", exact: true }).click();
  await page.getByRole("menuitem", { name: "요약 작업 추가", exact: true }).click();
  await expect.poll(async () => (await stored()).data.tasks.length).toBe(2);
  const nested = (await stored()).data.tasks.find((task) => task.parentExternalId === summary.externalId)!;
  const nestedRow = page.locator(`.wx-table-container .wx-row[data-id=":${nested.taskId}"]`);
  await expect(nestedRow).toBeVisible();
  await expect(page.locator(".wx-bar")).toHaveCount(0);
  expect((await row.boundingBox())!.height).toBe((await nestedRow.boundingBox())!.height);
  await row.locator('[data-action="open-task"]').click();
  await expect(nestedRow).toHaveCount(0);
  await row.locator('[data-action="open-task"]').click();
  await expect(nestedRow).toBeVisible();
  await page.screenshot({ path: "output/playwright/issue345-nested-1440.png" });
  const movedInstance = await frame.getAttribute("data-project-gantt-api-instance");
  await nestedRow.locator('[data-action="add-task"]').click();
  const leafName = page.getByRole("grid").getByText("새 작업", { exact: true });
  await expect(leafName).toBeVisible();
  await leafName.click({ button: "right" });
  await page.getByRole("menu", { name: "작업 메뉴", exact: true }).getByRole("menuitem", { name: "Outdent", exact: true }).click();
  await expect.poll(async () => (await stored()).data.tasks.find((task) => task.taskId === nested.taskId)?.start).toBeNull();
  await expect(nestedRow).toBeVisible();
  await expect(page.locator(`.wx-bar[data-task-id=":${nested.taskId}"]`)).toHaveCount(0);
  await expect(page.locator(`.wx-bar[data-task-id=":${summary.taskId}"]`)).toHaveCount(1);
  await expect(frame).toHaveAttribute("data-project-gantt-api-instance", movedInstance!);
  await page.reload();
  await expect(page.locator(`.wx-bar[data-task-id=":${nested.taskId}"]`)).toHaveCount(0);
  const moved = await stored();
  expect(moved.data.tasks.find((task) => task.name === "새 작업")?.parentExternalId).toBe(summary.externalId);
});
