import { expect, test, isolatedApplicationOptions } from "./fixtures/isolated-application";
import type { ProjectSnapshotResponse, ProjectTaskDto } from "../../src/contracts/projects";
import type { ResourceDashboardDto } from "../../src/contracts/resource-dashboard";
import type { ResourceDrillQueryInput, ResourceDrillQueryResponse, ResourceDrillScopeDto } from "../../src/contracts/resource-drill";
const password = "Synthetic528Admin!";
test.use({ ...isolatedApplicationOptions, isolatedResourceAdminPassword: password });

test("#528 실제 Chromium·SQLite 정확한 scope·Origin·stale·무변경·재시작", async ({ page, baseURL, browser, restartIsolatedApplication }, testInfo) => {
  test.setTimeout(180_000);
  const origin = baseURL!;
  const created = await page.request.post("/api/projects", { headers: { Origin: origin }, data: { name: "Resource Drill API #528", ownerName: "E2E", description: "synthetic", editPassword: "API527!" } }); expect(created.status()).toBe(201);
  const publicId = (await created.json()).data.project.publicId as string, api = `/api/projects/${publicId}`;
  const get = async () => (await (await page.request.get(api)).json()) as ProjectSnapshotResponse;
  let snapshot = await get();
  const mutate = async (path: string, data: unknown, method: "post" | "put" | "patch" = "post", expected = 200) => { const response = await page.request[method](`${api}${path}`, { headers: { Origin: origin, "If-Match": `"${snapshot.data.project.revision}"` }, data }); expect(response.status(), await response.text()).toBe(expected); snapshot = await get(); return response; };
  const add = async (name: string, type: "task" | "milestone" = "task", start = "2026-10-19") => { const response = await mutate("/tasks", { name, type, start, duration: type === "task" ? 1 : 0, progress: 0 }, "post", 201); return (await response.json()).data.tasks.find((task: ProjectTaskDto) => task.name === name) as ProjectTaskDto; };
  const a = await add("M1 80%"), b = await add("M2 60%"), outside = await add("기간 밖 이력", "task", "2025-01-06"), m1 = await add("Milestone 1", "milestone"), m2 = await add("Milestone 2", "milestone");
  await mutate("/milestone-memberships", { changes: [{ taskId: a.taskId, milestoneTaskId: m1.taskId }, { taskId: b.taskId, milestoneTaskId: m2.taskId }] });
  expect((await page.request.post("/api/resource-catalog/admin-sessions", { headers: { Origin: origin }, data: { password } })).status()).toBe(201);
  let catalog = (await (await page.request.get("/api/resources")).json()).data;
  const catalogMutate = async (path: string, data: unknown, method: "post" | "put" = "post", expected = 201) => { const response = await page.request[method](path, { headers: { Origin: origin, "If-Match": `"${catalog.revision}"` }, data }); expect(response.status(), await response.text()).toBe(expected); catalog = (await response.json()).data; };
  const ids: string[] = [];
  for (const code of ["R1", "R0", "HIDDEN"]) { await catalogMutate("/api/resources", { name: code, code, roles: ["DEVELOPER"], developerGrade: "ADVANCED" }); ids.push(catalog.resources.find((r: { code: string }) => r.code === code).id as string); }
  const [r1, r0] = ids;
  await catalogMutate("/api/resource-groups", { name: "Plan Group", code: "PG" }); const groupId = catalog.groups.find((g: { code: string }) => g.code === "PG").id as string;
  await catalogMutate(`/api/resource-groups/${groupId}/members`, { resourceIds: ids }, "put", 200);
  for (const [task, id, percent] of [[a, r1, 80], [b, r1, 60], [outside, r0, 50]] as const) await mutate(`/tasks/${task.taskId}/assignments`, { catalogRevision: catalog.revision, targets: [{ kind: "resource", id, allocation: { start: null, end: null, percent } }] }, "put");
  const readonly = await browser.newContext({ baseURL: origin });
  try {
    const publicPage = await readonly.newPage(); await publicPage.goto("/");
    const filters = { from: "2026-10-19", to: "2026-10-20", mdPerMm: null, granularity: "week" as const, milestoneIds: [m1.taskId] };
    const params = new URLSearchParams({ from: filters.from, to: filters.to, mdPerMm: "null", granularity: "week", milestoneIds: m1.taskId });
    const initial = await readonly.request.get(`${api}/resource-dashboard?${params}`); expect(initial.status()).toBe(200);
    const report = (await initial.json()).data as ResourceDashboardDto;
    const bootstrap = (await (await readonly.request.get(`${api}/resource-dashboard/scope?view=context`)).json()).data;
    expect(report.resourceScopeContext).toMatchObject(bootstrap);
    const legacy = (await (await readonly.request.get(`${api}/milestone-dashboard?from=${filters.from}&to=${filters.to}&mdPerMm=null`)).json()).data;
    expect(legacy.resourceScopeContext.dataSnapshotId).toBe(bootstrap.dataSnapshotId);
    const scopeParams = new URLSearchParams({ ...Object.fromEntries(params), view: "dashboard", snapshotId: report.snapshotId, dimension: "resource", id: r1 });
    const selectedScope = (await (await readonly.request.get(`${api}/resource-dashboard/scope?${scopeParams}`)).json()).data as ResourceDrillScopeDto;
    expect(selectedScope.taskIds).toEqual([a.taskId]); expect(selectedScope.assignmentCount).toBe(1);
    const body: ResourceDrillQueryInput = { sourceContext: selectedScope.sourceContext, scope: { kind: "exactAssignments", assignmentIds: selectedScope.assignmentIds }, filters, projection: { kind: "report" } };
    const fetched = await publicPage.evaluate(async ({ path, body }) => { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); return { status: response.status, cache: response.headers.get("cache-control"), nosniff: response.headers.get("x-content-type-options"), body: await response.json() }; }, { path: `${api}/resource-dashboard/query`, body });
    expect(fetched).toMatchObject({ status: 200, cache: "private, no-store", nosniff: "nosniff" });
    const scoped = fetched.body as ResourceDrillQueryResponse; expect((scoped.data as ResourceDashboardDto).summary.assignmentCount).toBe(1); expect(scoped.drill.sourceContext).toEqual(body.sourceContext);
    const scopedReport = scoped.data as ResourceDashboardDto;
    expect(scopedReport.plan!.resources.find(row => row.resourceId === r1)!.summary.project.knownMd).toBeCloseTo(1.4);
    const projection = { kind: "scope" as const, target: "plan" as const, snapshotId: scopedReport.snapshotId, granularity: "week" as const, periodId: "all", demandScope: "project" as const, selector: { kind: "resource" as const, resourceId: r1 }, date: filters.from };
    const projectScopeResponse = await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin }, data: { ...body, projection } }); expect(projectScopeResponse.status()).toBe(200);
    const projectScope = (await projectScopeResponse.json()).data as ResourceDrillScopeDto;
    expect(projectScope.taskIds.sort()).toEqual([a.taskId, b.taskId].sort()); expect(projectScope.assignmentCount).toBe(2); expect(projectScope.sourceContext.sourceProjection).toMatchObject({ kind: "plan", demandScope: "project", date: filters.from });
    expect((await readonly.request.post(`${api}/resource-dashboard/query`, { data: body })).status()).toBe(403);
    expect((await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: "http://evil.example" }, data: body })).status()).toBe(403);
    expect((await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin, "Content-Type": "text/plain" }, data: JSON.stringify(body) })).status()).toBe(415);
    expect((await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin, "Content-Type": "application/json" }, data: " ".repeat(1024 * 1024 + 1) })).status()).toBe(413);
    expect((await readonly.request.get(`${api}/resource-dashboard/query`)).status()).toBe(405);
    expect((await readonly.request.post(`${api}/resource-dashboard/scope`)).status()).toBe(405);
    const foreign = { ...body, scope: { kind: "exactAssignments", assignmentIds: ["00000000-0000-4000-8000-000000000001"] } };
    expect((await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin }, data: foreign })).status()).toBe(400);
    expect((await readonly.request.patch(`${api}/tasks/${a.taskId}`, { headers: { Origin: origin, "If-Match": `"${report.projectRevision}"` }, data: { name: "Denied" } })).status()).toBe(401);
    expect(await readonly.cookies()).toEqual([]); expect((await get()).data.project.revision).toBe(report.projectRevision);
    await restartIsolatedApplication();
    const restarted = await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin }, data: body }); expect(restarted.status()).toBe(200); expect((await restarted.json()).data.snapshotId).toBe(scopedReport.snapshotId);
    await mutate(`/tasks/${a.taskId}`, { name: "Changed source528" }, "patch");
    const stale = await readonly.request.post(`${api}/resource-dashboard/query`, { headers: { Origin: origin }, data: foreign }); expect(stale.status()).toBe(409); expect((await stale.json()).error.code).toBe("REPORT_STALE");
    expect(stale.headers()["cache-control"]).toBe("private, no-store"); expect(stale.headers()["set-cookie"]).toBeUndefined();
    await testInfo.attach("actual-528-readonly-api", { body: JSON.stringify({ bootstrap, selectedScope, scopedSnapshot: scopedReport.snapshotId, projectScope, revision: report.projectRevision }), contentType: "application/json" });
  } finally { await readonly.close(); }
});
