"use client";
import { useRouter } from "next/navigation";
import { useRef,useState,type FormEvent } from "react";
import { WorkspaceDialog } from "@/components/workspace-dialog";
import { useWorkspaceNotifications } from "@/components/workspace-notifications";
import type { CopyProjectResponse,ProjectSnapshotResponse } from "@/contracts/projects";
type Props=Readonly<{snapshot:ProjectSnapshotResponse;enabled:boolean;busy:boolean}>;
function validPassword(v:string){return Array.from(v).length>=12&&new TextEncoder().encode(v).byteLength<=1024}
function suggestedName(name:string){const suffix=" (복사본)";return `${Array.from(name).slice(0,200-Array.from(suffix).length).join("")}${suffix}`}
export function ProjectCopyButton({snapshot,enabled,busy}:Props){const router=useRouter(),{notify}=useWorkspaceNotifications();const[open,setOpen]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[resetProgress,setResetProgress]=useState(false),[copying,setCopying]=useState(false),[error,setError]=useState<string|null>(null);const trigger=useRef<HTMLButtonElement|null>(null);const{project,tasks,links}=snapshot.data;function show(){setName(suggestedName(project.name));setDescription(project.description);setPassword("");setConfirm("");setResetProgress(false);setError(null);setOpen(true)}function close(){if(!copying)setOpen(false)}async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const normalizedName=name.trim();if(!normalizedName||Array.from(normalizedName).length>200){setError("새 프로젝트명은 1~200자로 입력해 주세요.");return}if(Array.from(description).length>4000){setError("설명은 4,000자 이하여야 합니다.");return}if(!validPassword(password)||password!==confirm){setError("새 편집 비밀번호는 12자 이상이어야 하며 확인 값과 일치해야 합니다.");return}setCopying(true);setError(null);try{const response=await fetch(`/api/projects/${encodeURIComponent(project.publicId)}/copy`,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json","If-Match":`"${project.revision}"`},body:JSON.stringify({name:normalizedName,description,editPassword:password,resetProgress})});const body:unknown=await response.json().catch(()=>null);const data=typeof body==="object"&&body!==null&&"data"in body?(body as CopyProjectResponse).data:null;if(response.status===201&&data?.operation.kind==="projectCopy"){notify("success","프로젝트 복사본을 생성했습니다. 새 프로젝트로 이동합니다.","프로젝트 복사");router.push(`/projects/${encodeURIComponent(data.project.publicId)}`);return}setError(response.status===412?"원본 프로젝트가 변경되었습니다. 최신 정보를 확인한 뒤 다시 시도해 주세요.":response.status===401?"편집 권한이 만료되었습니다. 다시 잠금을 해제해 주세요.":"프로젝트를 복사하지 못했습니다.");notify("error","프로젝트를 복사하지 못했습니다.","프로젝트 복사",body)}catch{setError("네트워크 연결을 확인한 뒤 다시 시도해 주세요.")}finally{setCopying(false);setPassword("");setConfirm("")}}
return <><button ref={trigger} type="button" className="secondary-button" disabled={!enabled||busy} onClick={show}>프로젝트 복사</button>{open?<WorkspaceDialog title="프로젝트 복사" onClose={close} busy={copying} restoreFocusRef={trigger}><p>작업 {tasks.length} · 연결 {links.length} · 휴일 {project.calendar.holidays.length}. 서버에 저장된 일정과 계층을 독립 복사합니다.</p>{error?<p role="alert">{error}</p>:null}<form className="project-form compact-form" noValidate onSubmit={submit}><div className="form-field"><label htmlFor="detail-copy-name">새 프로젝트명</label><input id="detail-copy-name" value={name} disabled={copying} onChange={e=>setName(e.target.value)}/></div><div className="form-field"><label htmlFor="detail-copy-description">설명</label><textarea id="detail-copy-description" rows={3} value={description} disabled={copying} onChange={e=>setDescription(e.target.value)}/></div><div className="form-field"><label htmlFor="detail-copy-password">새 편집 비밀번호</label><input id="detail-copy-password" type="password" autoComplete="new-password" value={password} disabled={copying} onChange={e=>setPassword(e.target.value)}/></div><div className="form-field"><label htmlFor="detail-copy-password-confirm">새 편집 비밀번호 확인</label><input id="detail-copy-password-confirm" type="password" autoComplete="new-password" value={confirm} disabled={copying} onChange={e=>setConfirm(e.target.value)}/></div><label><input type="checkbox" checked={resetProgress} disabled={copying} onChange={e=>setResetProgress(e.target.checked)}/> 진척률 0%로 초기화</label><button className="primary-button" type="submit" disabled={copying}>{copying?"복사 중…":"복사본 생성"}</button></form></WorkspaceDialog>:null}</>}
