"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import type { LogisticsTypeCatalogItemDto, LogisticsTypeCatalogResponse, LogisticsTypeKind } from "@/contracts/logistics";
import { WorkspaceDialog } from "@/components/workspace-dialog";
import styles from "./logistics-type-catalog-admin.module.css";

function validCatalog(value:unknown):value is LogisticsTypeCatalogResponse{
  if(!value||typeof value!=="object"||!("data" in value))return false;
  const data=value.data;return !!data&&typeof data==="object"&&"revision" in data&&typeof data.revision==="number"&&Number.isSafeInteger(data.revision)&&
    "equipmentTypes" in data&&Array.isArray(data.equipmentTypes)&&"systemTypes" in data&&Array.isArray(data.systemTypes);
}
function etag(revision:number){return `"${revision}"`;}

export function LogisticsTypeCatalogAdmin(){
  const [authenticated,setAuthenticated]=useState(false);
  const [catalog,setCatalog]=useState<LogisticsTypeCatalogResponse|null>(null);
  const [state,setState]=useState<"loading"|"ready"|"error">("error");
  const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const [password,setPassword]=useState("");const [kind,setKind]=useState<LogisticsTypeKind>("equipment");
  const [code,setCode]=useState("");const [name,setName]=useState("");const [sortOrder,setSortOrder]=useState(0);
  const [editing,setEditing]=useState<LogisticsTypeCatalogItemDto|null>(null);const [editName,setEditName]=useState("");
  const [passwordOpen,setPasswordOpen]=useState(false);const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");
  const request=useRef<AbortController|null>(null);const loginRef=useRef<HTMLInputElement|null>(null);const passwordButtonRef=useRef<HTMLButtonElement|null>(null);
  useEffect(()=>()=>request.current?.abort(),[]);

  function begin(){if(busy)return null;const c=new AbortController();request.current=c;setBusy(true);setError(null);setNotice(null);return c;}
  function end(c:AbortController){if(!c.signal.aborted)setBusy(false);}
  function expire(){setAuthenticated(false);setCatalog(null);setState("error");setError("관리자 세션이 만료되었습니다. 다시 로그인해 주세요.");queueMicrotask(()=>loginRef.current?.focus());}
  async function load(c:AbortController){setState("loading");try{const r=await fetch("/api/logistics-catalog/admin/equipment-types",{credentials:"same-origin",cache:"no-store",signal:c.signal});const body:unknown=await r.json().catch(()=>null);if(r.status===401){expire();return false;}if(!r.ok||!validCatalog(body)){setState("error");setError("최신 물류 유형 목록을 불러오지 못했습니다.");return false;}setCatalog(body);setState("ready");return true;}catch{if(!c.signal.aborted){setState("error");setError("물류 유형 카탈로그에 연결할 수 없습니다.");}return false;}}
  async function login(e:FormEvent){e.preventDefault();const c=begin();if(!c)return;const submitted=password;setPassword("");try{const r=await fetch("/api/logistics-catalog/admin-sessions",{method:"POST",credentials:"same-origin",signal:c.signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({password:submitted})});if(!r.ok){setError("물류 관리자 인증에 실패했습니다.");return;}setAuthenticated(true);await load(c);}catch{if(!c.signal.aborted)setError("물류 관리자 인증 서버에 연결할 수 없습니다.");}finally{end(c);}}
  async function mutate(url:string,method:"POST"|"PATCH",body:unknown){if(!catalog||state!=="ready")return false;const c=begin();if(!c)return false;try{const r=await fetch(url,{method,credentials:"same-origin",signal:c.signal,headers:{"Content-Type":"application/json","If-Match":etag(catalog.data.revision)},body:JSON.stringify(body)});const value:unknown=await r.json().catch(()=>null);if(r.status===401){expire();return false;}if(r.status===412){await load(c);setError("다른 관리 변경이 먼저 저장되어 최신 목록을 다시 불러왔습니다.");return false;}if(!r.ok||!validCatalog(value)){setError("변경사항을 저장하지 못했습니다. 입력값과 중복 코드를 확인해 주세요.");return false;}setCatalog(value);setState("ready");setNotice("변경사항을 저장했습니다.");return true;}catch{if(!c.signal.aborted){setState("error");setError("변경 결과를 확인할 수 없습니다.");}return false;}finally{end(c);}}
  async function add(e:FormEvent){e.preventDefault();if(!code.trim()||!name.trim())return;const endpoint=kind==="equipment"?"equipment-types":"system-types";if(await mutate(`/api/logistics-catalog/admin/${endpoint}`,"POST",{code:code.trim(),name:name.trim(),sortOrder})){setCode("");setName("");setSortOrder(0);}}
  async function saveEdit(e:FormEvent){e.preventDefault();if(!editing||!editName.trim())return;const endpoint=kind==="equipment"?"equipment-types":"system-types";if(await mutate(`/api/logistics-catalog/admin/${endpoint}/${encodeURIComponent(editing.code)}`,"PATCH",{name:editName.trim()}))setEditing(null);}
  async function toggle(item:LogisticsTypeCatalogItemDto){const endpoint=kind==="equipment"?"equipment-types":"system-types";await mutate(`/api/logistics-catalog/admin/${endpoint}/${encodeURIComponent(item.code)}`,"PATCH",{active:!item.active});}
  function closePasswordDialog(){if(busy)return;setPasswordOpen(false);setNewPassword("");setConfirmPassword("");}
  async function changePassword(e:FormEvent){e.preventDefault();if(newPassword!==confirmPassword||Array.from(newPassword).length<1||Array.from(newPassword).length>12){setError("새 비밀번호는 1~12자이며 확인 값이 일치해야 합니다.");return;}const c=begin();if(!c)return;try{const r=await fetch("/api/logistics-catalog/admin-password",{method:"PUT",credentials:"same-origin",signal:c.signal,headers:{"Content-Type":"application/json"},body:JSON.stringify({newPassword,confirmPassword})});if(r.status===401){expire();return;}if(!r.ok){setError("관리자 비밀번호를 변경하지 못했습니다.");return;}setPasswordOpen(false);setNotice("관리자 비밀번호를 변경했습니다.");}catch{setError("비밀번호 변경 결과를 확인할 수 없습니다.");}finally{setNewPassword("");setConfirmPassword("");end(c);}}
  async function logout(){const c=begin();if(!c)return;try{const r=await fetch("/api/logistics-catalog/admin-sessions",{method:"DELETE",credentials:"same-origin",signal:c.signal});if(!r.ok)setError("서버 로그아웃을 확인하지 못했습니다. 관리 화면을 잠갔습니다.");}catch{if(!c.signal.aborted)setError("서버 로그아웃을 확인하지 못했습니다. 관리 화면을 잠갔습니다.");}finally{if(!c.signal.aborted){setAuthenticated(false);setCatalog(null);setState("error");setPassword("");setNewPassword("");setConfirmPassword("");end(c);}}}

  if(!authenticated)return <form className={styles.login} onSubmit={login}><h2>관리자 로그인</h2><p>프로젝트 편집 권한과 별도의 글로벌 물류 관리자 권한이 필요합니다.</p>{error?<p className={styles.error} role="alert">{error}</p>:null}<label>관리자 비밀번호<input ref={loginRef} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/></label><button className="primary-button" type="submit" disabled={busy||!password}>로그인</button></form>;
  if(!catalog)return <div className={styles.panel}>{error?<p className={styles.error} role="alert">{error}</p>:null}<button className="secondary-button" onClick={()=>{const c=begin();if(c)void load(c).finally(()=>end(c));}}>다시 시도</button></div>;

  const items=kind==="equipment"?catalog.data.equipmentTypes:catalog.data.systemTypes;
  return <div className={styles.panel}>
    <div className={styles.toolbar}><div className={styles.tabs}><button type="button" className={kind==="equipment"?"primary-button":"secondary-button"} onClick={()=>setKind("equipment")}>설비 유형</button><button type="button" className={kind==="system"?"primary-button":"secondary-button"} onClick={()=>setKind("system")}>시스템 유형</button></div><div className={styles.actions}><button ref={passwordButtonRef} className="secondary-button" type="button" onClick={()=>setPasswordOpen(true)}>관리자 비밀번호 변경</button><button className="secondary-button" type="button" onClick={()=>{const c=begin();if(c)void load(c).finally(()=>end(c));}}>새로고침</button><button className="secondary-button" type="button" onClick={()=>void logout()}>로그아웃</button></div></div>
    {error?<p className={styles.error} role="alert">{error}</p>:null}{notice?<p className={styles.note} role="status">{notice}</p>:null}{state!=="ready"?<p className={styles.note}>최신 목록을 확인하기 전에는 변경할 수 없습니다.</p>:null}
    <form className={styles.addRow} onSubmit={add}><label>유형명<input value={name} maxLength={200} onChange={e=>setName(e.target.value)} disabled={busy||state!=="ready"}/></label><label>코드<input value={code} maxLength={64} onChange={e=>setCode(e.target.value)} disabled={busy||state!=="ready"} placeholder="예: shuttle"/></label><label>정렬<input type="number" min={0} value={sortOrder} onChange={e=>setSortOrder(Math.max(0,Number(e.target.value)||0))} disabled={busy||state!=="ready"}/></label><button className="primary-button" type="submit" disabled={busy||state!=="ready"||!name.trim()||!code.trim()}>유형 추가</button></form>
    <div className={styles.tableWrap}><table><thead><tr><th>표시명</th><th>코드</th><th>상태</th><th>사용 건수</th><th>작업</th></tr></thead><tbody>{items.map(item=><tr key={item.code}><td>{item.name}</td><td><code>{item.code}</code></td><td>{item.active?"활성":"비활성"}</td><td>{item.usageCount}</td><td><div className={styles.actions}><button className="secondary-button" type="button" disabled={busy||state!=="ready"} onClick={()=>{setEditing(item);setEditName(item.name);}}>이름 수정</button><button className="secondary-button" type="button" disabled={busy||state!=="ready"} onClick={()=>void toggle(item)}>{item.active?"비활성화":"재활성화"}</button></div></td></tr>)}</tbody></table>{items.length===0?<p className={styles.note}>등록된 유형이 없습니다.</p>:null}</div>
    {editing?<WorkspaceDialog title="유형 이름 수정" busy={busy} onClose={()=>setEditing(null)}><form className={styles.dialog} onSubmit={saveEdit}><label>표시명<input autoFocus value={editName} maxLength={200} onChange={e=>setEditName(e.target.value)}/></label><div className={styles.actions}><button className="secondary-button" type="button" onClick={()=>setEditing(null)}>취소</button><button className="primary-button" type="submit" disabled={busy||!editName.trim()}>저장</button></div></form></WorkspaceDialog>:null}
    {passwordOpen?<WorkspaceDialog title="관리자 비밀번호 변경" restoreFocusRef={passwordButtonRef} busy={busy} onClose={closePasswordDialog}><form className={styles.dialog} onSubmit={changePassword}><label>새 비밀번호<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>새 비밀번호 확인<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><div className={styles.actions}><button className="secondary-button" type="button" onClick={closePasswordDialog}>취소</button><button className="primary-button" type="submit" disabled={busy||!newPassword||newPassword!==confirmPassword}>변경</button></div></form></WorkspaceDialog>:null}
  </div>;
}
