import type { ILink,ITask } from "@svar-ui/react-gantt";
import type { ProjectCalendarDto,ProjectLinkDto,ProjectTaskDto } from "../../contracts/projects";
import { addCalendarDays,createWorkingCalendar,workingDaysBetween } from "../../domain/scheduling";
import type { LocalTaskUpdateCommand } from "./command-gateway";
import { dateOnlyFromLocalDate,domainDatesToSvarDates,type DateOnly } from "./date-adapter";
function dateOnly(value:string):DateOnly{return value as DateOnly}
export interface ProjectTaskUpdatePayload { readonly name?:string;readonly progress?:number;readonly start?:string;readonly duration?:number;readonly description?:string|null;readonly url?:string|null }
export interface ProjectTaskUpdateCommand { readonly taskId:string;readonly payload:ProjectTaskUpdatePayload }
export interface ProjectTaskCreateCommand { readonly name:string;readonly type:"task";readonly start:string;readonly duration:number;readonly progress:0;readonly parentTaskId?:string;readonly convertParentToSummary?:true }
export function projectTasksToSvarTasks(tasks:readonly ProjectTaskDto[]):ITask[]{const ids=new Map(tasks.map(t=>[t.externalId,t.taskId]));return tasks.map(t=>({id:t.taskId,text:t.name,...domainDatesToSvarDates({start:dateOnly(t.start),end:dateOnly(t.end)}),progress:t.progress,type:t.type,parent:t.parentExternalId===null?0:ids.get(t.parentExternalId)??0,open:t.type==="summary",externalId:t.externalId}))}
export function projectLinksToSvarLinks(links:readonly ProjectLinkDto[],tasks:readonly ProjectTaskDto[]):ILink[]{const ids=new Map(tasks.map(t=>[t.externalId,t.taskId]));return links.flatMap(l=>{const source=ids.get(l.predecessorExternalId),target=ids.get(l.successorExternalId);return source===undefined||target===undefined?[]:[{id:l.id,source,target,type:"e2s"}]})}
function calendarFromDto(c:ProjectCalendarDto){return createWorkingCalendar({timezone:c.timezone,weekendDays:c.weekendDays,holidays:c.holidays})}
function durationFromRange(start:string,end:string,c:ProjectCalendarDto){return workingDaysBetween(start,end,calendarFromDto(c))}
function dateFromSvarExclusiveEnd(v:Date){return addCalendarDays(dateOnlyFromLocalDate(v),-1)}
export function translateProjectTaskUpdate(local:LocalTaskUpdateCommand,task:ProjectTaskDto,calendar:ProjectCalendarDto):ProjectTaskUpdateCommand|null{if(typeof local.taskId!=="string"||local.taskId!==task.taskId||task.type==="summary")return null;const payload:{name?:string;progress?:number;start?:string;duration?:number}={};if(typeof local.changes.text==="string"&&local.changes.text!==task.name)payload.name=local.changes.text;if(typeof local.changes.progress==="number"&&local.changes.progress!==task.progress)payload.progress=local.changes.progress;const{start:changedStart,end:changedEnd}=local.changes;const nextStart=changedStart instanceof Date?dateOnlyFromLocalDate(changedStart):undefined;const nextEnd=changedEnd instanceof Date?dateFromSvarExclusiveEnd(changedEnd):undefined;const startChanged=nextStart!==undefined&&nextStart!==task.start,endChanged=nextEnd!==undefined&&nextEnd!==task.end;if(task.type==="milestone"){if(startChanged)payload.start=nextStart;return Object.keys(payload).length?{taskId:task.taskId,payload}:null}if(typeof local.diff==="number"){if(startChanged&&endChanged)payload.start=nextStart;else if(startChanged){payload.start=nextStart;payload.duration=durationFromRange(nextStart,task.end,calendar)}else if(endChanged)payload.duration=durationFromRange(task.start,nextEnd,calendar)}else if(startChanged||endChanged){const start=nextStart??task.start,end=nextEnd??task.end;if(startChanged)payload.start=start;if(endChanged||startChanged)payload.duration=durationFromRange(start,end,calendar)}return Object.keys(payload).length?{taskId:task.taskId,payload}:null}
