import type Database from "better-sqlite3";

export interface TaskRecord { id:number; projectId:number; externalId:string; publicId:string; name:string; type:"task"|"summary"|"milestone"; scheduleMode:"auto"|"manual"; requestedStart:string|null; startDate:string; endDate:string; duration:number; progress:number; description:string|null; url:string|null; parentId:number|null; sortOrder:number; createdAt:string; updatedAt:string }
export interface LinkRecord { id:number; publicId:string; projectId:number; predecessorTaskId:number; successorTaskId:number; type:"FS"; lag:0; createdAt:string; updatedAt:string }
export interface HolidayRecord { id:number; projectId:number; holidayDate:string; name:string|null; createdAt:string }
export interface NewTaskRecord { projectId:number; externalId:string; publicId:string; name:string; type:"task"|"milestone"; scheduleMode:"auto"|"manual"; requestedStart:string; startDate:string; endDate:string; duration:number; progress:number; description?:string|null; url?:string|null; parentId:number|null; sortOrder:number; createdAt:string; updatedAt:string }
export type UpdatedTaskRecord = Omit<NewTaskRecord,"projectId"|"externalId"|"publicId"|"parentId"|"sortOrder"|"createdAt">;
export interface NewLinkRecord { publicId:string; projectId:number; predecessorTaskId:number; successorTaskId:number; type:"FS"; lag:0; createdAt:string; updatedAt:string }
export type UpdatedLinkRecord = Pick<NewLinkRecord,"predecessorTaskId"|"successorTaskId"|"type"|"lag"|"updatedAt">;
type TaskRow={id:number;project_id:number;external_id:string;public_id:string;name:string;type:TaskRecord["type"];schedule_mode:TaskRecord["scheduleMode"];requested_start:string|null;start_date:string;end_date:string;duration:number;progress:number;description:string|null;url:string|null;parent_id:number|null;sort_order:number;created_at:string;updated_at:string};
type LinkRow={id:number;public_id:string;project_id:number;predecessor_task_id:number;successor_task_id:number;type:"FS";lag:0;created_at:string;updated_at:string};
type HolidayRow={id:number;project_id:number;holiday_date:string;name:string|null;created_at:string};
function mapTask(r:TaskRow):TaskRecord{return{id:r.id,projectId:r.project_id,externalId:r.external_id,publicId:r.public_id,name:r.name,type:r.type,scheduleMode:r.schedule_mode,requestedStart:r.requested_start,startDate:r.start_date,endDate:r.end_date,duration:r.duration,progress:r.progress,description:r.description??null,url:r.url??null,parentId:r.parent_id,sortOrder:r.sort_order,createdAt:r.created_at,updatedAt:r.updated_at}}
function mapLink(r:LinkRow):LinkRecord{return{id:r.id,publicId:r.public_id,projectId:r.project_id,predecessorTaskId:r.predecessor_task_id,successorTaskId:r.successor_task_id,type:r.type,lag:r.lag,createdAt:r.created_at,updatedAt:r.updated_at}}
function mapHoliday(r:HolidayRow):HolidayRecord{return{id:r.id,projectId:r.project_id,holidayDate:r.holiday_date,name:r.name,createdAt:r.created_at}}
export class ScheduleRepository{
 constructor(private readonly database:Database.Database){}
 listTasks(projectId:number){return(this.database.prepare(`SELECT * FROM tasks WHERE project_id = ? ORDER BY parent_id IS NOT NULL, parent_id, sort_order, id`).all(projectId) as TaskRow[]).map(mapTask)}
 findTaskByPublicId(projectId:number,taskPublicId:string){const r=this.database.prepare("SELECT * FROM tasks WHERE project_id = ? AND public_id = ?").get(projectId,taskPublicId) as TaskRow|undefined;return r?mapTask(r):undefined}
 findTaskByExternalId(projectId:number,externalId:string){const r=this.database.prepare("SELECT * FROM tasks WHERE project_id = ? AND external_id = ?").get(projectId,externalId) as TaskRow|undefined;return r?mapTask(r):undefined}
 taskPublicIdExists(taskPublicId:string){return this.database.prepare("SELECT 1 FROM tasks WHERE public_id = ?").pluck().get(taskPublicId)===1}
 countTasks(projectId:number){return this.database.prepare("SELECT count(*) FROM tasks WHERE project_id = ?").pluck().get(projectId) as number}
 nextRootSortOrder(projectId:number){return this.nextSiblingSortOrder(projectId,null)}
 nextSiblingSortOrder(projectId:number,parentId:number|null){return this.database.prepare("SELECT COALESCE(MAX(sort_order), -1) + 1 FROM tasks WHERE project_id = ? AND parent_id IS ?").pluck().get(projectId,parentId) as number}
 insertTask(task:NewTaskRecord){const result=this.database.prepare(`INSERT INTO tasks (project_id,external_id,public_id,name,type,schedule_mode,requested_start,start_date,end_date,duration,progress,description,url,parent_id,sort_order,created_at,updated_at) VALUES (@projectId,@externalId,@publicId,@name,@type,@scheduleMode,@requestedStart,@startDate,@endDate,@duration,@progress,@description,@url,@parentId,@sortOrder,@createdAt,@updatedAt)`).run({...task,description:task.description??null,url:task.url??null});const r=this.database.prepare("SELECT * FROM tasks WHERE id = ?").get(Number(result.lastInsertRowid)) as TaskRow|undefined;if(!r)throw new Error("Inserted task could not be read back.");return mapTask(r)}
 updateTask(projectId:number,taskPublicId:string,task:UpdatedTaskRecord){const result=this.database.prepare(`UPDATE tasks SET name=@name,type=@type,schedule_mode=@scheduleMode,requested_start=@requestedStart,start_date=@startDate,end_date=@endDate,duration=@duration,progress=@progress,description=@description,url=@url,updated_at=@updatedAt WHERE project_id=@projectId AND public_id=@taskPublicId`).run({...task,description:task.description??null,url:task.url??null,projectId,taskPublicId});return result.changes===1?this.findTaskByPublicId(projectId,taskPublicId):undefined}
 renameTask(projectId:number,taskPublicId:string,name:string,updatedAt:string){const result=this.database.prepare(`UPDATE tasks SET name=?, updated_at=? WHERE project_id=? AND public_id=?`).run(name,updatedAt,projectId,taskPublicId);return result.changes===1?this.findTaskByPublicId(projectId,taskPublicId):undefined}
 updateTaskDetails(projectId:number,taskPublicId:string,details:{name?:string;description?:string|null;url?:string|null},updatedAt:string){const current=this.findTaskByPublicId(projectId,taskPublicId);if(!current)return undefined;const result=this.database.prepare(`UPDATE tasks SET name=@name,description=@description,url=@url,updated_at=@updatedAt WHERE project_id=@projectId AND public_id=@taskPublicId`).run({projectId,taskPublicId,name:details.name??current.name,description:details.description===undefined?current.description:details.description,url:details.url===undefined?current.url:details.url,updatedAt});return result.changes===1?this.findTaskByPublicId(projectId,taskPublicId):undefined}
 convertTaskToSummary(projectId:number,taskPublicId:string,updatedAt:string){return this.database.prepare(`UPDATE tasks SET type='summary',schedule_mode='auto',requested_start=NULL,updated_at=? WHERE project_id=? AND public_id=? AND type='task'`).run(updatedAt,projectId,taskPublicId).changes===1}
 updateSummarySchedule(projectId:number,taskPublicId:string,s:{startDate:string;endDate:string;duration:number;progress:number;updatedAt:string}){return this.database.prepare(`UPDATE tasks SET schedule_mode='auto',requested_start=NULL,start_date=@startDate,end_date=@endDate,duration=@duration,progress=@progress,updated_at=@updatedAt WHERE project_id=@projectId AND public_id=@taskPublicId AND type='summary'`).run({...s,projectId,taskPublicId}).changes===1}
 deleteTask(projectId:number,taskPublicId:string){return this.database.prepare("DELETE FROM tasks WHERE project_id=? AND public_id=?").run(projectId,taskPublicId).changes===1}
 listLinks(projectId:number){return(this.database.prepare(`SELECT * FROM links WHERE project_id=? ORDER BY id`).all(projectId) as LinkRow[]).map(mapLink)}
 findLinkByPublicId(projectId:number,linkPublicId:string){const r=this.database.prepare("SELECT * FROM links WHERE project_id=? AND public_id=?").get(projectId,linkPublicId) as LinkRow|undefined;return r?mapLink(r):undefined}
 listIncidentLinks(projectId:number,taskId:number){return(this.database.prepare(`SELECT * FROM links WHERE project_id=? AND (predecessor_task_id=? OR successor_task_id=?) ORDER BY id`).all(projectId,taskId,taskId) as LinkRow[]).map(mapLink)}
 insertLink(link:NewLinkRecord){const result=this.database.prepare(`INSERT INTO links (public_id,project_id,predecessor_task_id,successor_task_id,type,lag,created_at,updated_at) VALUES (@publicId,@projectId,@predecessorTaskId,@successorTaskId,@type,@lag,@createdAt,@updatedAt)`).run(link);const r=this.database.prepare("SELECT * FROM links WHERE id=?").get(Number(result.lastInsertRowid)) as LinkRow|undefined;if(!r)throw new Error("Inserted link could not be read back.");return mapLink(r)}
 updateLink(projectId:number,linkPublicId:string,link:UpdatedLinkRecord){const result=this.database.prepare(`UPDATE links SET predecessor_task_id=@predecessorTaskId,successor_task_id=@successorTaskId,type=@type,lag=@lag,updated_at=@updatedAt WHERE project_id=@projectId AND public_id=@linkPublicId`).run({...link,projectId,linkPublicId});return result.changes===1?this.findLinkByPublicId(projectId,linkPublicId):undefined}
 deleteLink(projectId:number,linkPublicId:string){return this.database.prepare("DELETE FROM links WHERE project_id=? AND public_id=?").run(projectId,linkPublicId).changes===1}
 listHolidays(projectId:number){return(this.database.prepare(`SELECT * FROM project_holidays WHERE project_id=? ORDER BY holiday_date,id`).all(projectId) as HolidayRow[]).map(mapHoliday)}
}
